import { useEffect, useMemo, useState } from "react";
import { Eye, FileDown, Plus, Save, Send, ShieldCheck, Trash2 } from "lucide-react";
import type { AppUser, School, SchoolYear } from "../../types";
import { previewOutgoingCorrespondence, outgoingRecipientLines } from "./outgoingCorrespondencePdf";
import type { AnnouncedCorrespondenceAttachment, Correspondence, CorrespondenceCopy, CorrespondenceStatus, OutgoingCorrespondenceData } from "./secretaryTypes";
import { SecretaryAiAssistant } from "./SecretaryAiAssistant";

const today = () => new Date().toISOString().slice(0, 10);
const uid = () => globalThis.crypto?.randomUUID?.() ?? `${Date.now()}-${Math.random()}`;
const correspondenceTypes = [
  ["administrative_letter", "Lettre administrative"], ["official_request", "Demande officielle"], ["administrative_response", "Réponse administrative"], ["transmission_letter", "Lettre de transmission"], ["summons", "Convocation"], ["notification", "Notification"], ["formal_notice", "Mise en demeure"], ["information_letter", "Lettre d’information"], ["other", "Autre courrier sortant"],
] as const;
const salutations = ["Monsieur le Directeur,", "Madame la Directrice,", "Monsieur l’Inspecteur,", "Madame l’Inspectrice,", "Monsieur,", "Madame,", "Madame, Monsieur,", "Mesdames et Messieurs,"];
const closings = ["Veuillez agréer, Monsieur le Directeur, l’expression de notre haute considération.", "Veuillez agréer, Madame la Directrice, l’expression de notre considération distinguée.", "Nous vous prions d’agréer, Monsieur, l’expression de nos salutations distinguées.", "Recevez, Madame, Monsieur, l’assurance de notre parfaite considération."];

function initialOutgoing(user: AppUser, school: School, year: SchoolYear): OutgoingCorrespondenceData {
  return {
    correspondenceType: "administrative_letter", issuePlace: school.address?.split(",")[0]?.trim() || "", academicYearName: year.name, authorName: user.name,
    priority: "normal", confidentiality: "public", deliveryMode: "hand_delivery", recipient: { salutation: "mr" }, salutation: salutations[0], introduction: "", mainMessage: "", conclusion: "", closingFormula: closings[0],
    signer: { userId: "", fullName: "", functionTitle: "", signatureType: "handwritten_space", signatureRequired: true, stampRequired: true, signatureSpace: "medium" }, visa: { required: false },
    announcedAttachments: [], copies: [], sendingChannel: "physical", receiptRequired: false, keywords: [], version: 1,
  };
}

export type OutgoingSaveRequest = { item: Correspondence; status: CorrespondenceStatus };

export function OutgoingCorrespondenceForm({ user, users, school, year, current, busy, onCancel, onSave }: {
  user: AppUser; users: AppUser[]; school: School; year: SchoolYear; current: Correspondence | null; busy: boolean;
  onCancel: () => void; onSave: (request: OutgoingSaveRequest) => Promise<void>;
}) {
  const [date, setDate] = useState(current?.date ?? today());
  const [subject, setSubject] = useState(current?.subject ?? "");
  const [outgoing, setOutgoing] = useState<OutgoingCorrespondenceData>(() => current?.outgoing ?? initialOutgoing(user, school, year));
  const [error, setError] = useState("");
  const [previewing, setPreviewing] = useState(false);
  const [dirty, setDirty] = useState(false);
  const locked = current?.status === "archived" || (current?.status && current.status !== "draft");
  const signers = useMemo(() => users.filter((entry) => entry.schoolId === school.id && entry.status !== "inactive" && ["school_admin", "secretary", "discipline_director"].includes(entry.role)), [school.id, users]);
  const aiSections = { Objet: subject, "Formule d’appel": outgoing.salutation, Introduction: outgoing.introduction, "Message principal": outgoing.mainMessage, "Détails et modalités": outgoing.details ?? "", Justification: outgoing.justification ?? "", "Suite attendue": outgoing.expectedFollowUp ?? "", Conclusion: outgoing.conclusion, "Formule de politesse": outgoing.closingFormula };

  const set = <K extends keyof OutgoingCorrespondenceData>(key: K, value: OutgoingCorrespondenceData[K]) => { setDirty(true); setOutgoing((previous) => ({ ...previous, [key]: value })); };
  useEffect(() => {
    const warn = (event: BeforeUnloadEvent) => { if (dirty && !locked) event.preventDefault(); };
    window.addEventListener("beforeunload", warn); return () => window.removeEventListener("beforeunload", warn);
  }, [dirty, locked]);
  const cancel = () => { if (!dirty || locked || window.confirm("Quitter sans enregistrer les modifications ?")) onCancel(); };
  const item = (): Correspondence => ({
    id: current?.id ?? "preview", referenceNumber: current?.referenceNumber ?? "Attribuée lors de l’enregistrement", direction: "outgoing", date, subject,
    sender: school.name, recipient: outgoing.recipient.fullName || outgoing.recipient.functionTitle || "", content: [outgoing.introduction, outgoing.mainMessage, outgoing.details, outgoing.justification, outgoing.expectedFollowUp, outgoing.conclusion].filter(Boolean).join("\n\n"),
    status: current?.status ?? "draft", createdBy: current?.createdBy ?? user.id, createdAt: current?.createdAt ?? new Date().toISOString(), updatedAt: new Date().toISOString(), schoolId: school.id, schoolYearId: year.id, outgoing,
  });
  function validate() {
    if (!outgoing.correspondenceType || !date || !outgoing.issuePlace.trim() || (!outgoing.recipient.functionTitle?.trim() && !outgoing.recipient.fullName?.trim()) || !subject.trim() || !outgoing.salutation.trim() || !outgoing.introduction.trim() || !outgoing.mainMessage.trim() || !outgoing.conclusion.trim() || !outgoing.closingFormula.trim() || !outgoing.signer.userId || !outgoing.signer.fullName.trim() || !outgoing.signer.functionTitle.trim()) return "Renseignez tous les champs obligatoires du courrier.";
    if (outgoing.correspondenceType === "other" && !outgoing.customCorrespondenceType?.trim()) return "Précisez le type de courrier.";
    if (outgoing.recipient.salutation === "other" && !outgoing.recipient.customSalutation?.trim()) return "Précisez la civilité.";
    if (outgoing.sendingChannel === "email" && !outgoing.recipientEmail?.trim()) return "L’adresse e-mail du destinataire est obligatoire pour un envoi par e-mail.";
    return "";
  }
  async function act(status: CorrespondenceStatus) {
    const validation = validate(); if (validation) { setError(validation); return; }
    setError(""); await onSave({ item: item(), status });
  }
  async function preview() {
    const validation = validate(); if (validation) { setError(validation); return; }
    setPreviewing(true); setError("");
    try { await previewOutgoingCorrespondence(item(), school, year); } catch (cause) { setError(cause instanceof Error ? cause.message : "Impossible de prévisualiser le courrier."); } finally { setPreviewing(false); }
  }
  const recipient = outgoing.recipient;
  function acceptAi(section: string, value: string) {
    const keys: Record<string, keyof OutgoingCorrespondenceData> = { "Formule d’appel": "salutation", Introduction: "introduction", "Message principal": "mainMessage", "Détails et modalités": "details", Justification: "justification", "Suite attendue": "expectedFollowUp", Conclusion: "conclusion", "Formule de politesse": "closingFormula" };
    if (section === "Objet") { setDirty(true); setSubject(value); }
    else if (keys[section]) set(keys[section], value as never);
  }

  return <form className="grid gap-5" onSubmit={(event) => { event.preventDefault(); void act("draft"); }}>
    {error && <p role="alert" className="rounded border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</p>}
    {!locked && <div className="flex justify-end"><SecretaryAiAssistant user={user} schoolId={school.id} academicYearId={year.id} documentId={current?.id} documentType="outgoing_correspondence" sections={aiSections} onAccept={acceptAi} /></div>}
    <fieldset disabled={Boolean(locked) || busy} className="grid gap-5 disabled:opacity-75">
      <FormSection title="1. Identification"><Select label="Type de courrier *" value={outgoing.correspondenceType} onChange={(value) => set("correspondenceType", value as OutgoingCorrespondenceData["correspondenceType"])} options={correspondenceTypes} />{outgoing.correspondenceType === "other" && <Field label="Préciser le type de courrier *" value={outgoing.customCorrespondenceType ?? ""} onChange={(value) => set("customCorrespondenceType", value)} />}<ReadOnly label="Référence du courrier" value={current?.referenceNumber ?? "Attribuée lors de l’enregistrement"} /><Field label="Date du courrier *" type="date" value={date} onChange={setDate} /><Field label="Lieu d’émission *" value={outgoing.issuePlace} onChange={(value) => set("issuePlace", value)} /><ReadOnly label="Année scolaire" value={year.name} /><ReadOnly label="Auteur" value={user.name} /><ReadOnly label="Statut" value={statusLabel(current?.status ?? "draft")} /></FormSection>
      <FormSection title="2. Destinataire"><Select label="Civilité" value={recipient.salutation} onChange={(value) => set("recipient", { ...recipient, salutation: value as typeof recipient.salutation })} options={[["mr", "Monsieur"], ["mrs", "Madame"], ["ladies_gentlemen", "Mesdames et Messieurs"], ["other", "Autre"]]} />{recipient.salutation === "other" && <Field label="Préciser la civilité" value={recipient.customSalutation ?? ""} onChange={(value) => set("recipient", { ...recipient, customSalutation: value })} />}<Field label="Fonction ou qualité du destinataire *" value={recipient.functionTitle ?? ""} onChange={(value) => set("recipient", { ...recipient, functionTitle: value })} /><Field label="Nom complet du destinataire" value={recipient.fullName ?? ""} onChange={(value) => set("recipient", { ...recipient, fullName: value })} /><Field label="Institution ou organisme" value={recipient.institution ?? ""} onChange={(value) => set("recipient", { ...recipient, institution: value })} /><Area label="Adresse du destinataire" value={recipient.address ?? ""} onChange={(value) => set("recipient", { ...recipient, address: value })} /><Field label="Ville ou localité" value={recipient.city ?? ""} onChange={(value) => set("recipient", { ...recipient, city: value })} /><Field label="Pays" value={recipient.country ?? ""} onChange={(value) => set("recipient", { ...recipient, country: value })} /><div className="rounded border bg-slate-50 p-3"><strong className="text-sm">Aperçu du destinataire</strong>{outgoingRecipientLines(item()).map((line) => <div key={line}>{line}</div>)}</div></FormSection>
      <FormSection title="3. Mentions administratives"><Select label="Niveau de priorité" value={outgoing.priority} onChange={(value) => set("priority", value as OutgoingCorrespondenceData["priority"])} options={[["normal", "Normale"], ["important", "Importante"], ["urgent", "Urgente"], ["very_urgent", "Très urgente"]]} /><Select label="Niveau de confidentialité" value={outgoing.confidentiality} onChange={(value) => set("confidentiality", value as OutgoingCorrespondenceData["confidentiality"])} options={[["public", "Public"], ["internal", "Interne"], ["confidential", "Confidentiel"], ["strictly_confidential", "Strictement confidentiel"]]} /><Select label="Mode d’acheminement" value={outgoing.deliveryMode} onChange={(value) => set("deliveryMode", value)} options={[["hand_delivery", "Remise en main propre"], ["mail", "Par courrier"], ["email", "Par e-mail"], ["hierarchical", "Par voie hiérarchique"], ["acknowledgment", "Avec accusé de réception"], ["other", "Autre"]]} />{outgoing.deliveryMode === "other" && <Field label="Préciser le mode" value={outgoing.customDeliveryMode ?? ""} onChange={(value) => set("customDeliveryMode", value)} />}<Field label="Sous couvert de" value={outgoing.underCoverOf ?? ""} onChange={(value) => set("underCoverOf", value)} /><Select label="Mention spéciale" value={outgoing.specialMention ?? ""} onChange={(value) => set("specialMention", value)} options={[["", "Aucune"], ["urgent", "Urgent"], ["confidential", "Confidentiel"], ["very_urgent", "Très urgent"], ["useful_action", "Pour suite utile"], ["information", "Pour information"], ["hierarchical", "Par voie hiérarchique"], ["other", "Autre"]]} />{outgoing.specialMention === "other" && <Field label="Préciser la mention" value={outgoing.customSpecialMention ?? ""} onChange={(value) => set("customSpecialMention", value)} />}</FormSection>
      <FormSection title="4. Objet et références"><Field label="Objet *" value={subject} onChange={setSubject} maxLength={220} /><Field label="Référence antérieure" value={outgoing.previousReference ?? ""} onChange={(value) => set("previousReference", value)} /><DynamicAnnounced value={outgoing.announcedAttachments} onChange={(value) => set("announcedAttachments", value)} /></FormSection>
      <FormSection title="5. Corps du courrier"><Select label="Formule d’appel *" value={salutations.includes(outgoing.salutation) ? outgoing.salutation : "other"} onChange={(value) => set("salutation", value === "other" ? "" : value)} options={[...salutations.map((value) => [value, value] as const), ["other", "Autre"]]} />{!salutations.includes(outgoing.salutation) && <Field label="Saisir la formule d’appel *" value={outgoing.salutation} onChange={(value) => set("salutation", value)} />}<Area label="Introduction ou contexte *" value={outgoing.introduction} onChange={(value) => set("introduction", value)} /><Area label="Demande, information ou décision principale *" value={outgoing.mainMessage} onChange={(value) => set("mainMessage", value)} /><Area label="Détails et modalités" value={outgoing.details ?? ""} onChange={(value) => set("details", value)} /><Area label="Motivation ou justification" value={outgoing.justification ?? ""} onChange={(value) => set("justification", value)} /><Area label="Suite attendue" value={outgoing.expectedFollowUp ?? ""} onChange={(value) => set("expectedFollowUp", value)} /><Area label="Conclusion *" value={outgoing.conclusion} onChange={(value) => set("conclusion", value)} /></FormSection>
      <FormSection title="6. Formule de politesse"><Select label="Formule de politesse *" value={closings.includes(outgoing.closingFormula) ? outgoing.closingFormula : "other"} onChange={(value) => set("closingFormula", value === "other" ? "" : value)} options={[...closings.map((value) => [value, value] as const), ["other", "Autre"]]} />{!closings.includes(outgoing.closingFormula) && <Area label="Formule personnalisée *" value={outgoing.closingFormula} onChange={(value) => set("closingFormula", value)} />}</FormSection>
      <FormSection title="7. Signataire"><Select label="Signataire *" value={outgoing.signer.userId} onChange={(value) => { const selected = signers.find((entry) => entry.id === value); set("signer", { ...outgoing.signer, userId: value, fullName: selected?.name ?? "", functionTitle: roleLabel(selected?.role) }); }} options={[["", "Sélectionner"], ...signers.map((entry) => [entry.id, `${entry.name} — ${roleLabel(entry.role)}`] as const)]} /><Field label="Nom complet du signataire *" value={outgoing.signer.fullName} onChange={(value) => set("signer", { ...outgoing.signer, fullName: value })} /><Field label="Fonction du signataire *" value={outgoing.signer.functionTitle} onChange={(value) => set("signer", { ...outgoing.signer, functionTitle: value })} /><Select label="Type de signature" value={outgoing.signer.signatureType} onChange={(value) => set("signer", { ...outgoing.signer, signatureType: value as typeof outgoing.signer.signatureType })} options={[["stored", "Signature enregistrée"], ["handwritten_space", "Espace pour signature manuscrite"], ["none", "Sans signature intégrée"]]} /><YesNo label="Signature requise" value={outgoing.signer.signatureRequired} onChange={(value) => set("signer", { ...outgoing.signer, signatureRequired: value })} /><YesNo label="Cachet requis" value={outgoing.signer.stampRequired} onChange={(value) => set("signer", { ...outgoing.signer, stampRequired: value })} /><Select label="Taille de l’espace de signature" value={outgoing.signer.signatureSpace} onChange={(value) => set("signer", { ...outgoing.signer, signatureSpace: value as typeof outgoing.signer.signatureSpace })} options={[["small", "Petit"], ["medium", "Moyen"], ["large", "Grand"]]} /></FormSection>
      <FormSection title="8. Visa éventuel"><YesNo label="Visa requis" value={outgoing.visa.required} onChange={(value) => set("visa", { ...outgoing.visa, required: value })} />{outgoing.visa.required && <><Field label="Nom de la personne chargée du visa" value={outgoing.visa.personName ?? ""} onChange={(value) => set("visa", { ...outgoing.visa, personName: value })} /><Field label="Fonction" value={outgoing.visa.functionTitle ?? ""} onChange={(value) => set("visa", { ...outgoing.visa, functionTitle: value })} /><Field label="Mention du visa" value={outgoing.visa.mention ?? ""} onChange={(value) => set("visa", { ...outgoing.visa, mention: value })} /><Field label="Date du visa" type="date" value={outgoing.visa.date ?? ""} onChange={(value) => set("visa", { ...outgoing.visa, date: value })} /></>}</FormSection>
      <FormSection title="9. Copies pour information"><DynamicCopies value={outgoing.copies} onChange={(value) => set("copies", value)} /></FormSection>
      <FormSection title="10. Mode d’envoi"><Select label="Canal d’envoi" value={outgoing.sendingChannel} onChange={(value) => set("sendingChannel", value)} options={[["physical", "Remise physique"], ["email", "E-mail"], ["postal", "Courrier postal"], ["acadea", "Messagerie interne Acadéa"], ["other", "Autre"]]} />{outgoing.sendingChannel === "other" && <Field label="Préciser le canal" value={outgoing.customSendingChannel ?? ""} onChange={(value) => set("customSendingChannel", value)} />}<Field label="Date d’envoi prévue" type="date" value={outgoing.plannedSendDate ?? ""} onChange={(value) => set("plannedSendDate", value)} />{outgoing.sendingChannel === "email" && <Field label="Adresse e-mail du destinataire" type="email" value={outgoing.recipientEmail ?? ""} onChange={(value) => set("recipientEmail", value)} />}<YesNo label="Accusé de réception requis" value={outgoing.receiptRequired} onChange={(value) => set("receiptRequired", value)} /><Select label="Personne chargée de l’envoi" value={outgoing.sentBy ?? ""} onChange={(value) => set("sentBy", value)} options={[["", "Non désignée"], ...signers.map((entry) => [entry.id, entry.name] as const)]} /><Field label="Date réelle d’envoi" type="date" value={outgoing.actualSendDate ?? ""} onChange={(value) => set("actualSendDate", value)} /><Field label="Date de réception confirmée" type="date" value={outgoing.confirmedReceptionDate ?? ""} onChange={(value) => set("confirmedReceptionDate", value)} /></FormSection>
      <FormSection title="11. Gestion interne"><Field label="Service émetteur" value={outgoing.issuingDepartment ?? ""} onChange={(value) => set("issuingDepartment", value)} /><Field label="Catégorie" value={outgoing.category ?? ""} onChange={(value) => set("category", value)} /><Field label="Dossier de classement" value={outgoing.filingFolder ?? ""} onChange={(value) => set("filingFolder", value)} /><Field label="Mots-clés (séparés par des virgules)" value={outgoing.keywords.join(", ")} onChange={(value) => set("keywords", value.split(",").map((entry) => entry.trim()).filter(Boolean))} /><Area label="Observations internes" value={outgoing.internalNotes ?? ""} onChange={(value) => set("internalNotes", value)} /><ReadOnly label="Créé par" value={user.name} /><ReadOnly label="Version" value={String(outgoing.version)} /></FormSection>
    </fieldset>
    <div className="sticky bottom-0 z-10 flex flex-wrap gap-2 border-t bg-white py-3">
      <button type="button" className="secondary-button" disabled={busy} onClick={cancel}>Annuler</button>
      {!locked && <button type="submit" className="secondary-button" disabled={busy}><Save className="h-4 w-4" /> Enregistrer comme brouillon</button>}
      <button type="button" className="secondary-button" disabled={busy || previewing} onClick={() => void preview()}><Eye className="h-4 w-4" /> Prévisualiser</button>
      {!locked && <button type="button" className="secondary-button" disabled={busy} onClick={() => void act("pending_validation")}><Send className="h-4 w-4" /> Soumettre à validation</button>}
      <button type="button" className="secondary-button" disabled={busy || previewing} onClick={() => void preview()}><FileDown className="h-4 w-4" /> Générer le PDF</button>
      {!locked && <button type="button" className="primary-button" disabled={busy} onClick={() => void act("validated")}><ShieldCheck className="h-4 w-4" /> Finaliser</button>}
    </div>
  </form>;
}

function FormSection({ title, children }: { title: string; children: React.ReactNode }) { return <section className="grid gap-3 rounded-lg border bg-white p-4"><h3 className="font-semibold text-slate-800">{title}</h3><div className="grid gap-3 md:grid-cols-2">{children}</div></section>; }
function Field({ label, value, onChange, type = "text", maxLength }: { label: string; value: string; onChange: (value: string) => void; type?: string; maxLength?: number }) { return <label className="grid min-w-0 gap-1 text-sm"><span>{label}</span><input className="input w-full" type={type} value={value} maxLength={maxLength} onChange={(event) => onChange(event.target.value)} /></label>; }
function Area({ label, value, onChange, assistant }: { label: string; value: string; onChange: (value: string) => void; assistant?: React.ReactNode }) { return <label className="grid min-w-0 gap-1 text-sm md:col-span-2"><span className="flex flex-wrap items-center justify-between gap-2">{label}{assistant}</span><textarea className="input min-h-24 w-full" value={value} onChange={(event) => onChange(event.target.value)} /></label>; }
function ReadOnly({ label, value }: { label: string; value: string }) { return <label className="grid gap-1 text-sm"><span>{label}</span><input className="input bg-slate-100" value={value} readOnly /></label>; }
function Select({ label, value, onChange, options }: { label: string; value: string; onChange: (value: string) => void; options: readonly (readonly [string, string])[] }) { return <label className="grid min-w-0 gap-1 text-sm"><span>{label}</span><select className="input w-full" value={value} onChange={(event) => onChange(event.target.value)}>{options.map(([option, caption]) => <option key={option} value={option}>{caption}</option>)}</select></label>; }
function YesNo({ label, value, onChange }: { label: string; value: boolean; onChange: (value: boolean) => void }) { return <Select label={label} value={value ? "yes" : "no"} onChange={(next) => onChange(next === "yes")} options={[["no", "Non"], ["yes", "Oui"]]} />; }
function DynamicAnnounced({ value, onChange }: { value: AnnouncedCorrespondenceAttachment[]; onChange: (value: AnnouncedCorrespondenceAttachment[]) => void }) { return <div className="grid gap-2 md:col-span-2"><div className="flex items-center justify-between"><strong className="text-sm">Pièces jointes annoncées</strong><button type="button" className="secondary-button" onClick={() => onChange([...value, { id: uid(), title: "", copies: 1, includeInPdf: true }])}><Plus className="h-4 w-4" /> Ajouter</button></div>{value.map((entry) => <div className="grid gap-2 rounded border p-2 sm:grid-cols-[1fr_110px_auto_auto]" key={entry.id}><input className="input" placeholder="Intitulé" value={entry.title} onChange={(event) => onChange(value.map((item) => item.id === entry.id ? { ...item, title: event.target.value } : item))} /><input className="input" aria-label="Nombre d’exemplaires" type="number" min="1" value={entry.copies} onChange={(event) => onChange(value.map((item) => item.id === entry.id ? { ...item, copies: Math.max(1, Number(event.target.value)) } : item))} /><label className="flex items-center gap-1 text-sm"><input type="checkbox" checked={entry.includeInPdf} onChange={(event) => onChange(value.map((item) => item.id === entry.id ? { ...item, includeInPdf: event.target.checked } : item))} /> PDF</label><button type="button" aria-label="Retirer" onClick={() => onChange(value.filter((item) => item.id !== entry.id))}><Trash2 className="h-4 w-4" /></button></div>)}</div>; }
function DynamicCopies({ value, onChange }: { value: CorrespondenceCopy[]; onChange: (value: CorrespondenceCopy[]) => void }) { return <div className="grid gap-2 md:col-span-2"><div className="flex items-center justify-between"><strong className="text-sm">Copies</strong><button type="button" className="secondary-button" onClick={() => onChange([...value, { id: uid(), nameOrFunction: "", includeInPdf: true }])}><Plus className="h-4 w-4" /> Ajouter</button></div>{value.map((entry) => <div className="grid gap-2 rounded border p-2 sm:grid-cols-3" key={entry.id}><input className="input" placeholder="Nom ou fonction" value={entry.nameOrFunction} onChange={(event) => onChange(value.map((item) => item.id === entry.id ? { ...item, nameOrFunction: event.target.value } : item))} /><input className="input" placeholder="Institution" value={entry.institution ?? ""} onChange={(event) => onChange(value.map((item) => item.id === entry.id ? { ...item, institution: event.target.value } : item))} /><input className="input" placeholder="Motif" value={entry.reason ?? ""} onChange={(event) => onChange(value.map((item) => item.id === entry.id ? { ...item, reason: event.target.value } : item))} /><label className="flex items-center gap-1 text-sm"><input type="checkbox" checked={entry.includeInPdf} onChange={(event) => onChange(value.map((item) => item.id === entry.id ? { ...item, includeInPdf: event.target.checked } : item))} /> Afficher dans le PDF</label><button type="button" className="secondary-button" onClick={() => onChange(value.filter((item) => item.id !== entry.id))}><Trash2 className="h-4 w-4" /> Retirer</button></div>)}</div>; }
function roleLabel(role?: AppUser["role"]) { return ({ school_admin: "Chef d’établissement", secretary: "Secrétaire", discipline_director: "Directeur de discipline" } as Partial<Record<AppUser["role"], string>>)[role ?? "parent"] ?? "Utilisateur autorisé"; }
function statusLabel(status: CorrespondenceStatus) { return ({ draft: "Brouillon", pending_validation: "En attente de validation", validated: "Validé", signed: "Signé", ready_to_send: "Prêt à envoyer", sent: "Envoyé", received: "Reçu", archived: "Archivé", cancelled: "Annulé" })[status]; }
