import { randomUUID } from "node:crypto";
import { FieldValue, getFirestore } from "firebase-admin/firestore";
import { logger } from "firebase-functions";
import { defineSecret } from "firebase-functions/params";
import { HttpsError, onCall } from "firebase-functions/v2/https";
import { assertStudyDirectorAiIdentity, assertStudyDirectorAiProfile } from "./schoolAiAccess.js";
import { completeSchoolAiUsage, prepareSchoolAiUsage, releaseSchoolAiUsage, reserveSchoolAiUsage, type AiUsageDatabase } from "./schoolAiUsage.js";
import { classifyOpenAiFailure, extractOpenAiResponseText, readOpenAiFailure } from "./openAiResponse.js";
import { assertActiveSchoolYear, type SchoolYearDatabase } from "../security/schoolYear.js";
import { enforceCallableRateLimit, FUNCTION_RATE_LIMITS, type RateLimitDatabase } from "../security/rateLimit.js";

const openAiApiKey = defineSecret("OPENAI_API_KEY");
const REGION = "europe-west1";
export const STUDY_AI_INTENTS = ["EXPLAIN_SCHEDULE","EXPLAIN_CONFLICT","REOPTIMIZE_TEACHER","REOPTIMIZE_CLASS","APPLY_AVAILABILITY_CONSTRAINT","PREFER_SUBJECT_TIME","MINIMIZE_CHANGES","SUMMARIZE_SCHEDULE","CHECK_FEASIBILITY","NEEDS_CLARIFICATION"] as const;
const MUTATING = new Set(["REOPTIMIZE_TEACHER","REOPTIMIZE_CLASS","APPLY_AVAILABILITY_CONSTRAINT","PREFER_SUBJECT_TIME","MINIMIZE_CHANGES"]);
const forbidden = /publie|publication directe|supprime|mot de passe|finance|autre école|ignore les règles/i;
type Intent = typeof STUDY_AI_INTENTS[number];
export type StudyAiResponse = { intent:Intent; explanation:string; entityType:"teacher"|"class"|"subject"|"room"|"none"; entityQuery:string; constraints:Array<{type:"UNAVAILABLE_DAY"|"UNAVAILABLE_AFTER"|"PREFER_MORNING"|"REDUCE_GAPS"|"DISTRIBUTE_SUBJECT";dayOfWeek:string;time:string}>;preferences:Array<{type:"MINIMIZE_CHANGES"|"PREFER_MORNING"|"REDUCE_GAPS"|"DISTRIBUTE_SUBJECT";weight:number}>;requiresConfirmation:boolean; clarificationOptions:string[] };
export const STUDY_RESPONSE_FORMAT={type:"json_schema",name:"acadea_study_assistant",strict:true,schema:{type:"object",additionalProperties:false,properties:{intent:{type:"string",enum:STUDY_AI_INTENTS},explanation:{type:"string"},entityType:{type:"string",enum:["teacher","class","subject","room","none"]},entityQuery:{type:"string"},constraints:{type:"array",items:{type:"object",additionalProperties:false,properties:{type:{type:"string",enum:["UNAVAILABLE_DAY","UNAVAILABLE_AFTER","PREFER_MORNING","REDUCE_GAPS","DISTRIBUTE_SUBJECT"]},dayOfWeek:{type:"string"},time:{type:"string"}},required:["type","dayOfWeek","time"]}},preferences:{type:"array",items:{type:"object",additionalProperties:false,properties:{type:{type:"string",enum:["MINIMIZE_CHANGES","PREFER_MORNING","REDUCE_GAPS","DISTRIBUTE_SUBJECT"]},weight:{type:"integer",minimum:1,maximum:10}},required:["type","weight"]}},requiresConfirmation:{type:"boolean"},clarificationOptions:{type:"array",items:{type:"string"}}},required:["intent","explanation","entityType","entityQuery","constraints","preferences","requiresConfirmation","clarificationOptions"]}} as const;

export function validateStudyAiInput(value:unknown){if(!value||typeof value!=="object")throw new HttpsError("invalid-argument","Demande IA invalide.");const x=value as Record<string,unknown>;if(typeof x.schoolId!=="string"||typeof x.schoolYearId!=="string"||typeof x.prompt!=="string"||!x.prompt.trim()||x.prompt.length>2000||typeof x.idempotencyKey!=="string")throw new HttpsError("invalid-argument","Paramètres IA invalides.");if(forbidden.test(x.prompt))throw new HttpsError("permission-denied","Cette action n’est pas autorisée par l’Assistant IA.");const context=x.context;if(!context||typeof context!=="object"||Array.isArray(context))throw new HttpsError("invalid-argument","Contexte pédagogique invalide.");const allowed=new Set(["sourceScheduleId","sourceStatus","entryCount","teachers","classes","subjects","rooms"]);for(const[key,item]of Object.entries(context)){if(!allowed.has(key)||(!(typeof item==="string"||typeof item==="number")&&!Array.isArray(item))||(Array.isArray(item)&&item.some(entry=>typeof entry!=="string"||entry.length>120)))throw new HttpsError("invalid-argument","Le contexte IA contient un champ non autorisé.");}return x as {schoolId:string;schoolYearId:string;prompt:string;idempotencyKey:string;context:Record<string,unknown>};}
export function validateStudyAiResponse(value:unknown):StudyAiResponse{if(!value||typeof value!=="object")throw new HttpsError("internal","Réponse IA structurée invalide.");const x=value as StudyAiResponse;if(!STUDY_AI_INTENTS.includes(x.intent)||typeof x.explanation!=="string"||!Array.isArray(x.constraints)||!Array.isArray(x.preferences)||!Array.isArray(x.clarificationOptions)||typeof x.requiresConfirmation!=="boolean"||!(["teacher","class","subject","room","none"] as string[]).includes(x.entityType))throw new HttpsError("internal","Réponse IA structurée invalide.");if(MUTATING.has(x.intent)!==x.requiresConfirmation)throw new HttpsError("internal","Confirmation IA incohérente.");return x;}
export function buildStudyOpenAiBody(input:ReturnType<typeof validateStudyAiInput>,model:string){return{model,store:false,instructions:"Tu es l’assistant de la Direction des études d’Acadéa. Interprète uniquement des demandes d’horaires scolaires. Ne publie, ne supprime et ne crée aucune entité. Retourne une intention structurée. Les noms restent des requêtes textuelles: n’invente jamais d’ID. Distingue contraintes fortes et préférences. Une mutation exige confirmation. Une ambiguïté produit NEEDS_CLARIFICATION. Réponds en français.",input:JSON.stringify({request:input.prompt,context:input.context}),text:{format:STUDY_RESPONSE_FORMAT}};}

export const studyAiAssistant=onCall({region:REGION,timeoutSeconds:60,memory:"256MiB",secrets:[openAiApiKey],invoker:"public"},async request=>{const started=Date.now(),requestId=randomUUID();const input=validateStudyAiInput(request.data);const db=getFirestore();const {auth,schoolId}=assertStudyDirectorAiIdentity(request.auth,input.schoolId);await assertActiveSchoolYear(db as unknown as SchoolYearDatabase,schoolId,input.schoolYearId);const profile=await db.doc(`users/${auth.uid}`).get();assertStudyDirectorAiProfile(profile.exists?profile.data():undefined,auth.uid,schoolId);await enforceCallableRateLimit({db:db as unknown as RateLimitDatabase,actorId:auth.uid,schoolId,action:"ai.study",idempotencyKey:input.idempotencyKey,...FUNCTION_RATE_LIMITS.AI_GENERATE});const usageDb=db as unknown as AiUsageDatabase;await prepareSchoolAiUsage(usageDb,schoolId);const apiKey=openAiApiKey.value();if(!apiKey)throw new HttpsError("failed-precondition","L’assistant IA n’est pas configuré.");await reserveSchoolAiUsage(usageDb,{schoolId,userId:auth.uid,idempotencyKey:input.idempotencyKey});let completed=false,result:StudyAiResponse|undefined;const model=process.env.OPENAI_MODEL||"gpt-5-mini";try{const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),45000);const response=await fetch("https://api.openai.com/v1/responses",{method:"POST",signal:controller.signal,headers:{Authorization:`Bearer ${apiKey}`,"Content-Type":"application/json"},body:JSON.stringify(buildStudyOpenAiBody(input,model))}).finally(()=>clearTimeout(timer));const provider=await response.json() as unknown;if(!response.ok){const failure=readOpenAiFailure(response.status,provider);logger.error("Study AI provider failure",{requestId,...failure});const mapped=classifyOpenAiFailure(response.status);throw new HttpsError(mapped.code,mapped.message,failure);}const text=extractOpenAiResponseText(provider);try{result=validateStudyAiResponse(JSON.parse(text));}catch(error){if(error instanceof HttpsError)throw error;throw new HttpsError("internal","Réponse IA structurée invalide.");}completed=true;await completeSchoolAiUsage(usageDb,schoolId,auth.uid,input.idempotencyKey);return{...result,requestId};}catch(error){if(!completed)await releaseSchoolAiUsage(usageDb,schoolId,auth.uid,input.idempotencyKey).catch(()=>undefined);if(error instanceof HttpsError)throw error;throw new HttpsError(error instanceof Error&&error.name==="AbortError"?"deadline-exceeded":"unavailable","L’Assistant IA est temporairement indisponible.");}finally{await db.collection("aiUsageLogs").doc(requestId).set({schoolId,schoolYearId:input.schoolYearId,userId:auth.uid,role:"study_director",action:result?.intent??"interpret",sourceScheduleId:(input.context.sourceScheduleId as string)||null,draftScheduleId:null,status:completed?"success":"failed",provider:"openai",model,durationMs:Date.now()-started,createdAt:FieldValue.serverTimestamp()}).catch(()=>undefined);}});
