import { useEffect, useMemo, useState } from "react";
import type { ReactNode } from "react";
import { BookOpen, CalendarRange, FileClock, Landmark, Network, Settings, UsersRound } from "lucide-react";
import { AdminDrawer, ImageUploadField } from "../../components/ui";
import type { AppUser, Coordination, School, SubCoordination } from "../../types";
import { loadCoordinationReadModel, type CoordinationReadModel } from "../../services/coordinationReadModel";
import { closeCoordinationSchoolYears, loadCoordinationSchoolYearStatus, openCoordinationSchoolYears, type CoordinationSchoolYearRow } from "../../services/coordinationSchoolYears";
import { updateCoordinationSettings } from "../../services/coordinationService";
import { escapePdfHtml, pdfSection, pdfTable, renderAcadPdfPreview } from "../../utils/pdf";
import { activityTimestamp, formatActivityDateTime } from "../../utils/activityHistory";
import { coordinationPdfInstitution } from "./coordinationPdfInstitution";
import { SubCoordinationManagement } from "./SubCoordinationManagement";

type Drawer = "fees" | "finance" | "personnel" | "years" | "settings" | "history" | "subCoordinations";
const emptyModel: CoordinationReadModel = { feeTypes: [], payments: [], expenses: [], personnel: [], schoolYears: [], auditLogs: [] };
const roleLabel: Record<string, string> = { school_admin: "Administrateur", cashier: "Caissier", discipline_director: "Directeur de discipline", study_director: "Directeur des études", secretary: "Secrétaire", teacher: "Enseignant", parent: "Parent" };

export function CoordinationMenu({ coordination, schools, selectedSchoolId, principalCoordinatorName, user, subCoordination }: { coordination: Coordination; schools: School[]; selectedSchoolId: string; principalCoordinatorName: string; user: AppUser; subCoordination?: SubCoordination | null }) {
  const [drawer, setDrawer] = useState<Drawer | null>(null);
  const [model, setModel] = useState<CoordinationReadModel>(emptyModel);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [search, setSearch] = useState("");
  const [personnelRole, setPersonnelRole] = useState("");
  const [personnelStatus, setPersonnelStatus] = useState("");
  const [from, setFrom] = useState("");
  const [to, setTo] = useState("");
  const [yearRows, setYearRows] = useState<CoordinationSchoolYearRow[]>([]);
  const [referenceYear, setReferenceYear] = useState<string | null>(null);
  const [yearName, setYearName] = useState("");
  const [startsAt, setStartsAt] = useState("");
  const [endsAt, setEndsAt] = useState("");
  const [yearBusy, setYearBusy] = useState(false);
  const [yearResults, setYearResults] = useState<Array<{ schoolId: string; status: string; reason?: string }>>([]);
  const [settingsForm, setSettingsForm] = useState({ name: coordination.name, code: coordination.code ?? "", phone: coordination.phone ?? "", email: coordination.email ?? "", address: coordination.address ?? "", logoUrl: coordination.logoUrl ?? "" });
  const [settingsBusy, setSettingsBusy] = useState(false);
  const schoolIds = useMemo(() => selectedSchoolId ? [selectedSchoolId] : schools.map((item) => item.id), [schools, selectedSchoolId]);

  useEffect(() => { setSettingsForm({ name: coordination.name, code: coordination.code ?? "", phone: coordination.phone ?? "", email: coordination.email ?? "", address: coordination.address ?? "", logoUrl: coordination.logoUrl ?? "" }); }, [coordination]);
  useEffect(() => {
    if (!drawer) return undefined;
    let cancelled = false; setLoading(true); setError("");
    loadCoordinationReadModel(coordination.id, schoolIds, user.subCoordinationId).then((result) => { if (!cancelled) setModel(result); }).catch((cause) => { if (!cancelled) setError(cause instanceof Error ? cause.message : "Chargement impossible."); }).finally(() => { if (!cancelled) setLoading(false); });
    if (drawer === "years") loadCoordinationSchoolYearStatus().then((result) => { if (!cancelled) { setYearRows(result.rows.filter((row) => schoolIds.includes(row.schoolId))); setReferenceYear(result.referenceYear); } }).catch(() => { if (!cancelled) setError("Années indisponibles."); });
    return () => { cancelled = true; };
  }, [coordination.id, drawer, schoolIds, user.subCoordinationId]);

  const schoolName = (id?: string) => schools.find((item) => item.id === id)?.name ?? id ?? "—";
  const fees = model.feeTypes.filter((item) => schoolIds.includes(item.schoolId));
  const payments = model.payments.filter((item) => schoolIds.includes(item.schoolId) && (!from || item.paidAt >= from) && (!to || item.paidAt <= to));
  const expenses = model.expenses.filter((item) => schoolIds.includes(item.schoolId) && (!from || item.spentAt >= from) && (!to || item.spentAt <= to));
  const personnel = model.personnel.filter((item) => { const inactive = item.active === false || item.status === "inactive"; return schoolIds.includes(item.schoolId ?? "") && (!personnelRole || item.role === personnelRole || (personnelRole === "school_admin" && (item.role as string) === "admin")) && (!personnelStatus || (personnelStatus === "inactive" ? inactive : !inactive)) && `${item.name} ${item.email ?? ""} ${item.role}`.toLowerCase().includes(search.toLowerCase()); });
  const logs = model.auditLogs.filter((item) => (user.role === "coordination_admin" ? (item.coordinationId === coordination.id || !item.schoolId || schoolIds.includes(item.schoolId)) : (item.subCoordinationId === user.subCoordinationId || Boolean(item.schoolId && schoolIds.includes(item.schoolId)))) && `${item.action} ${item.actorName ?? ""} ${item.details ?? ""}`.toLowerCase().includes(search.toLowerCase())).sort((a, b) => activityTimestamp(b.createdAt) - activityTimestamp(a.createdAt));
  const currencyOf = (id: string) => schools.find((item) => item.id === id)?.currency ?? "USD";
  const financialByCurrency = [...new Set([...payments.map((item) => currencyOf(item.schoolId)), ...expenses.map((item) => currencyOf(item.schoolId))])].sort().map((currency) => { const income = payments.filter((item) => currencyOf(item.schoolId) === currency).reduce((sum, item) => sum + item.amount, 0); const spending = expenses.filter((item) => currencyOf(item.schoolId) === currency).reduce((sum, item) => sum + item.amount, 0); return { currency, income, spending, balance: income - spending }; });
  const formatAmount = (value: number, currency: string) => `${value.toFixed(2)} ${currency}`;

  async function exportPdf(kind: Exclude<Drawer, "settings" | "subCoordinations">) {
    const contextSchool = schools.find((item) => item.id === selectedSchoolId) ?? schools[0]; if (!contextSchool) return;
    const context = selectedSchoolId ? contextSchool.name : "Toutes les écoles";
    const sections = kind === "fees" ? [pdfSection("Types de frais", pdfTable([{ header: "École", render: (item) => schoolName(item.schoolId) }, { header: "Type", render: (item) => item.name }, { header: "Montant", render: (item) => formatAmount(item.amount, currencyOf(item.schoolId)) }], fees, "Aucun type de frais."))]
      : kind === "finance" ? [pdfSection("Synthèse", pdfTable([{ header: "Devise", render: (item) => item.currency }, { header: "Recettes", render: (item) => formatAmount(item.income, item.currency) }, { header: "Dépenses", render: (item) => formatAmount(item.spending, item.currency) }, { header: "Solde", render: (item) => formatAmount(item.balance, item.currency) }], financialByCurrency, "Aucune opération.")), pdfSection("Paiements", pdfTable([{ header: "École", render: (item) => schoolName(item.schoolId) }, { header: "Date", render: (item) => item.paidAt }, { header: "Montant", render: (item) => formatAmount(item.amount, currencyOf(item.schoolId)) }], payments, "Aucun paiement.")), pdfSection("Dépenses", pdfTable([{ header: "École", render: (item) => schoolName(item.schoolId) }, { header: "Date", render: (item) => item.spentAt }, { header: "Montant", render: (item) => formatAmount(item.amount, currencyOf(item.schoolId)) }], expenses, "Aucune dépense."))]
      : kind === "personnel" ? [pdfSection("Personnels", pdfTable([{ header: "École", render: (item) => schoolName(item.schoolId) }, { header: "Nom", render: (item) => item.name }, { header: "Fonction", render: (item) => roleLabel[item.role] ?? item.role }, { header: "Statut", render: (item) => item.active === false || item.status === "inactive" ? "Inactif" : "Actif" }], personnel, "Aucun personnel."))]
      : kind === "years" ? [pdfSection("Années scolaires", pdfTable([{ header: "École", render: (item) => item.schoolName }, { header: "Année active", render: (item) => item.activeYear?.name ?? "Aucune" }, { header: "Alignement", render: (item) => !referenceYear || item.activeYear?.name === referenceYear ? "Alignée" : "Année scolaire non alignée" }], yearRows, "Aucune école."))]
      : [pdfSection("Historique", pdfTable([{ header: "Date", render: (item) => formatActivityDateTime(item.createdAt) }, { header: "École", render: (item) => schoolName(item.schoolId) }, { header: "Action", render: (item) => escapePdfHtml(item.action) }, { header: "Acteur", render: (item) => item.actorName ?? "—" }], logs, "Aucune activité."))];
    await renderAcadPdfPreview({ filename: `coordination-${kind}-${selectedSchoolId || "toutes"}.pdf`, title: `Coordination — ${kind}`, school: coordinationPdfInstitution(coordination, contextSchool), subtitle: context, sections });
  }

  async function saveSettings() { if (user.role !== "coordination_admin" || settingsBusy) return; setSettingsBusy(true); setError(""); try { await updateCoordinationSettings(settingsForm); } catch (cause) { setError(cause instanceof Error ? cause.message : "Enregistrement impossible."); } finally { setSettingsBusy(false); } }
  async function mutateYears(action: "close" | "open") { if (user.role !== "coordination_admin") { setError("La gouvernance annuelle reste réservée au Coordinateur principal."); return; } setYearBusy(true); try { const response = action === "close" ? await closeCoordinationSchoolYears() : await openCoordinationSchoolYears({ name: yearName, startsAt, endsAt }); setYearResults(response.results); } catch (cause) { setError(cause instanceof Error ? cause.message : "Opération impossible."); } finally { setYearBusy(false); } }

  const items = [["fees", "Types de frais", BookOpen], ["finance", "Rapport financier", Landmark], ["personnel", "Personnels", UsersRound], ["years", "Année scolaire", CalendarRange], ["settings", "Paramètres coordination", Settings], ["history", "Historique", FileClock], ...(user.role === "coordination_admin" ? [["subCoordinations", "Sous-coordinations", Network] as const] : [])] as const;
  function settingsContent(): ReactNode { if (subCoordination || user.role !== "coordination_admin") return <><p><b>{subCoordination ? "Circonscription" : "Coordination"} :</b> {subCoordination?.circumscription ?? coordination.name}</p>{subCoordination && <><p><b>Sous-coordinateur :</b> {user.name}</p><p><b>Statut :</b> {subCoordination.active ? "Actif" : "Archivé"}</p></>}<p><b>Écoles attribuées :</b> {schools.length}</p><p className="rounded bg-slate-50 p-3">Ces paramètres sont disponibles en lecture seule.</p></>; return <><label className="grid gap-1 font-semibold">Nom<input className="input" value={settingsForm.name} onChange={(event) => setSettingsForm({ ...settingsForm, name: event.target.value })} disabled={settingsBusy} /></label><label className="grid gap-1 font-semibold">Sigle / code<input className="input" value={settingsForm.code} onChange={(event) => setSettingsForm({ ...settingsForm, code: event.target.value })} disabled={settingsBusy} /></label><label className="grid gap-1 font-semibold">Téléphone<input className="input" value={settingsForm.phone} onChange={(event) => setSettingsForm({ ...settingsForm, phone: event.target.value })} disabled={settingsBusy} /></label><label className="grid gap-1 font-semibold">E-mail<input className="input" type="email" value={settingsForm.email} onChange={(event) => setSettingsForm({ ...settingsForm, email: event.target.value })} disabled={settingsBusy} /></label><label className="grid gap-1 font-semibold">Adresse<input className="input" value={settingsForm.address} onChange={(event) => setSettingsForm({ ...settingsForm, address: event.target.value })} disabled={settingsBusy} /></label><ImageUploadField label="Photo / Logo de la Coordination" value={settingsForm.logoUrl} onChange={(logoUrl) => setSettingsForm({ ...settingsForm, logoUrl })} maxWidth={700} maxBytes={250 * 1024} disabled={settingsBusy} previewFit="contain" /><p><b>Coordinateur principal :</b> {principalCoordinatorName || "Non renseigné"}</p><p><b>Écoles :</b> {schools.length} (lecture seule)</p><button type="button" className="primary-button justify-center" disabled={settingsBusy || !settingsForm.name.trim()} onClick={() => void saveSettings()}>{settingsBusy ? "Enregistrement…" : "Enregistrer les paramètres"}</button><p className="rounded bg-slate-50 p-3">Le rattachement des écoles reste réservé au Super Administrateur.</p></>; }
  function drawerContent(): ReactNode {
    if (drawer === "fees") return <><button className="pdf-export-button" type="button" onClick={() => void exportPdf("fees")}>Exporter PDF</button><ReadTable headers={["École", "Type", "Montant"]} rows={fees.map((item) => [schoolName(item.schoolId), String(item.name), formatAmount(item.amount, currencyOf(item.schoolId))])} /></>;
    if (drawer === "finance") return <><div className="grid grid-cols-2 gap-2"><input className="input" aria-label="Date de début" type="date" value={from} onChange={(event) => setFrom(event.target.value)} /><input className="input" aria-label="Date de fin" type="date" value={to} onChange={(event) => setTo(event.target.value)} /></div><ReadTable headers={["Devise", "Recettes", "Dépenses", "Solde"]} rows={financialByCurrency.map((item) => [item.currency, formatAmount(item.income, item.currency), formatAmount(item.spending, item.currency), formatAmount(item.balance, item.currency)])} /><button className="pdf-export-button" type="button" onClick={() => void exportPdf("finance")}>Exporter PDF</button></>;
    if (drawer === "personnel") return <><div className="grid gap-2 sm:grid-cols-3"><input className="input" placeholder="Rechercher" value={search} onChange={(event) => setSearch(event.target.value)} /><select className="input" aria-label="Filtrer par rôle" value={personnelRole} onChange={(event) => setPersonnelRole(event.target.value)}><option value="">Tous rôles</option>{Object.entries(roleLabel).map(([role, label]) => <option key={role} value={role}>{label}</option>)}</select><select className="input" aria-label="Filtrer par statut" value={personnelStatus} onChange={(event) => setPersonnelStatus(event.target.value)}><option value="">Tous statuts</option><option value="active">Actifs</option><option value="inactive">Inactifs</option></select></div><button className="pdf-export-button" type="button" onClick={() => void exportPdf("personnel")}>Exporter PDF</button><ReadTable headers={["École", "Nom", "Fonction", "Statut"]} rows={personnel.map((item) => [schoolName(item.schoolId), item.name, roleLabel[item.role] ?? item.role, item.active === false || item.status === "inactive" ? "Inactif" : "Actif"])} /></>;
    if (drawer === "years") return <><p className="rounded bg-blue-50 p-3 text-sm">Année de référence : <b>{referenceYear ?? "Non définie"}</b></p><button className="pdf-export-button" type="button" onClick={() => void exportPdf("years")}>Exporter PDF</button><ReadTable headers={["École", "Année active", "Alignement"]} rows={yearRows.map((item) => [item.schoolName, item.activeYear?.name ?? "Aucune", !referenceYear || item.activeYear?.name === referenceYear ? "Alignée" : "Année non alignée"])} />{yearResults.length > 0 && <ReadTable headers={["École", "Résultat", "Motif"]} rows={yearResults.map((item) => [schoolName(item.schoolId), item.status, item.reason ?? "—"])} />}{user.role === "coordination_admin" ? <><button className="secondary-button w-full justify-center" disabled={yearBusy} type="button" onClick={() => void mutateYears("close")}>Clôturer les années prêtes</button><div className="grid gap-2 rounded border p-3"><input className="input" placeholder="2027-2028" value={yearName} onChange={(event) => setYearName(event.target.value)} /><input className="input" type="date" value={startsAt} onChange={(event) => setStartsAt(event.target.value)} /><input className="input" type="date" value={endsAt} onChange={(event) => setEndsAt(event.target.value)} /><button className="primary-button justify-center" disabled={yearBusy || !yearName || !startsAt || !endsAt} type="button" onClick={() => void mutateYears("open")}>Ouvrir la nouvelle année</button></div></> : <p className="rounded border border-blue-100 bg-blue-50 p-3 text-sm">Consultation uniquement. L’ouverture et la clôture restent réservées au Coordinateur principal.</p>}</>;
    if (drawer === "settings") return <div className="grid gap-3 text-sm">{settingsContent()}</div>;
    if (drawer === "history") return <><input className="input" placeholder="Rechercher" value={search} onChange={(event) => setSearch(event.target.value)} /><button className="pdf-export-button" type="button" onClick={() => void exportPdf("history")}>Exporter PDF</button><ReadTable headers={["Date", "École", "Action", "Acteur"]} rows={logs.map((item) => [formatActivityDateTime(item.createdAt), schoolName(item.schoolId), item.action, item.actorName ?? "—"])} /></>;
    return user.role === "coordination_admin" ? <SubCoordinationManagement coordination={coordination} schools={schools} currentUser={user} /> : null;
  }
  return <section className="grid gap-4"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{items.map(([id, label, Icon]) => <button key={id} type="button" onClick={() => { setDrawer(id); setSearch(""); }} className="flex items-center gap-3 rounded border bg-white p-4 text-left shadow-sm hover:border-blue-300"><Icon className="h-5 w-5 text-blue-700" /><span className="font-semibold">{label}</span></button>)}</div>{drawer && <AdminDrawer title={items.find(([id]) => id === drawer)?.[1] ?? "Coordination"} closeLabel="Fermer" onClose={() => setDrawer(null)}>{error && <p role="alert" className="rounded bg-red-50 p-3 text-sm text-red-700">{error}</p>}{loading && <p className="text-sm text-slate-500">Chargement…</p>}{drawerContent()}</AdminDrawer>}</section>;
}

function ReadTable({ headers, rows }: { headers: string[]; rows: string[][] }) { return <div className="overflow-x-auto"><table className="w-full min-w-[560px] text-left text-sm"><thead><tr className="border-b">{headers.map((header) => <th key={header} className="p-2">{header}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr key={`${index}-${row.join("-")}`} className="border-b">{row.map((cell, cellIndex) => <td key={`${cellIndex}-${cell}`} className="p-2">{cell}</td>)}</tr>)}</tbody></table>{rows.length === 0 && <p className="p-4 text-sm text-slate-500">Aucune donnée.</p>}</div>; }
