import { useEffect, useMemo, useState } from "react";
import type { ReactNode } from "react";
import { BookOpen, CalendarRange, FileClock, Landmark, Network, Printer, Settings, UsersRound } from "lucide-react";
import { AdminDrawer, ImageUploadField, LogoutButton } from "../../components/ui";
import type { AppUser, Coordination, PersonnelProfile, School, SubCoordination } from "../../types";
import { loadCoordinationReadModel, type CoordinationReadModel } from "../../services/coordinationReadModel";
import { closeCoordinationSchoolYears, loadCoordinationSchoolYearStatus, openCoordinationSchoolYears, type CoordinationSchoolYearRow } from "../../services/coordinationSchoolYears";
import { loadCoordinationPersonnelProfile, updateCoordinationSettings } from "../../services/coordinationService";
import { escapePdfHtml, pdfSection, pdfTable, renderAcadPdfPreview } from "../../utils/pdf";
import { activityTimestamp, formatActivityDateTime } from "../../utils/activityHistory";
import { coordinationPdfInstitution } from "./coordinationPdfInstitution";
import { SubCoordinationManagement } from "./SubCoordinationManagement";
import { INTERNAL_PERSONNEL_ROLES, isInternalPersonnel, personnelRoleLabels } from "../../services/personnel";
import { PersonnelProfileReadOnly } from "../../components/personnel/PersonnelProfileReadOnly";
import { printPersonnelProfilePdf } from "../../utils/personnelPdf";
import { groupCoordinationFinancialsByCurrency } from "../../utils/coordinationFinancialsByCurrency";
import { formatCurrencyMoney } from "../../utils/currency";

type Drawer = "fees" | "finance" | "personnel" | "years" | "settings" | "history" | "subCoordinations";
const emptyModel: CoordinationReadModel = { students: [], feeTypes: [], payments: [], expenses: [], personnel: [], schoolYears: [], auditLogs: [] };
const roleLabel: Record<string, string> = personnelRoleLabels;

export function CoordinationMenu({ coordination, schools, selectedSchoolId, principalCoordinatorName, user, subCoordination, onLogout }: { coordination: Coordination; schools: School[]; selectedSchoolId: string; principalCoordinatorName: string; user: AppUser; subCoordination?: SubCoordination | null; onLogout: () => void }) {
  const [drawer, setDrawer] = useState<Drawer | null>(null);
  const [model, setModel] = useState<CoordinationReadModel>(emptyModel);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [search, setSearch] = useState("");
  const [personnelRole, setPersonnelRole] = useState("");
  const [personnelStatus, setPersonnelStatus] = useState("");
  const [from, setFrom] = useState("");
  const [to, setTo] = useState("");
  const [yearRows, setYearRows] = useState<CoordinationSchoolYearRow[]>([]);
  const [referenceYear, setReferenceYear] = useState<string | null>(null);
  const [yearName, setYearName] = useState("");
  const [startsAt, setStartsAt] = useState("");
  const [endsAt, setEndsAt] = useState("");
  const [yearBusy, setYearBusy] = useState(false);
  const [yearResults, setYearResults] = useState<Array<{ schoolId: string; status: string; reason?: string }>>([]);
  const [settingsForm, setSettingsForm] = useState({ name: coordination.name, code: coordination.code ?? "", phone: coordination.phone ?? "", email: coordination.email ?? "", address: coordination.address ?? "", logoUrl: coordination.logoUrl ?? "" });
  const [settingsBusy, setSettingsBusy] = useState(false);
  const [drawerSchoolId, setDrawerSchoolId] = useState(selectedSchoolId);
  const [selectedPersonnel, setSelectedPersonnel] = useState<AppUser>();
  const [selectedPersonnelProfile, setSelectedPersonnelProfile] = useState<PersonnelProfile>();
  const [personnelProfileReady, setPersonnelProfileReady] = useState(false);
  const allSchoolIds = useMemo(() => schools.map((item) => item.id), [schools]);
  const schoolIds = useMemo(() => drawerSchoolId ? [drawerSchoolId] : allSchoolIds, [allSchoolIds, drawerSchoolId]);

  useEffect(() => { setSettingsForm({ name: coordination.name, code: coordination.code ?? "", phone: coordination.phone ?? "", email: coordination.email ?? "", address: coordination.address ?? "", logoUrl: coordination.logoUrl ?? "" }); }, [coordination]);
  useEffect(() => {
    if (!drawer) return undefined;
    let cancelled = false; setLoading(true); setError("");
    loadCoordinationReadModel(coordination.id, allSchoolIds, user.subCoordinationId).then((result) => { if (!cancelled) setModel(result); }).catch((cause) => { if (!cancelled) setError(cause instanceof Error ? cause.message : "Chargement impossible."); }).finally(() => { if (!cancelled) setLoading(false); });
    if (drawer === "years") loadCoordinationSchoolYearStatus().then((result) => { if (!cancelled) { setYearRows(result.rows.filter((row) => allSchoolIds.includes(row.schoolId))); setReferenceYear(result.referenceYear); } }).catch(() => { if (!cancelled) setError("Années indisponibles."); });
    return () => { cancelled = true; };
  }, [allSchoolIds, coordination.id, drawer, user.subCoordinationId]);
  useEffect(() => {
    if (!selectedPersonnel?.schoolId) { setSelectedPersonnelProfile(undefined); setPersonnelProfileReady(false); return undefined; }
    let cancelled = false;
    setPersonnelProfileReady(false);
    loadCoordinationPersonnelProfile(selectedPersonnel.id).then((profile) => { if (!cancelled) setSelectedPersonnelProfile(profile ?? undefined); }).catch(() => { if (!cancelled) setError("Impossible de charger la fiche Personnel."); }).finally(() => { if (!cancelled) setPersonnelProfileReady(true); });
    return () => { cancelled = true; };
  }, [selectedPersonnel]);

  const schoolName = (id?: string) => schools.find((item) => item.id === id)?.name ?? id ?? "—";
  const scopedSchools = schools.filter((school) => schoolIds.includes(school.id));
  const activeYearBySchool = new Map(scopedSchools.map((school) => [school.id, school.activeSchoolYearId]));
  const inActiveSchoolYear = (item: { schoolId: string; schoolYearId: string }) => activeYearBySchool.get(item.schoolId) === item.schoolYearId;
  const students = model.students.filter((item) => inActiveSchoolYear(item) && (item.status ?? "ACTIVE") === "ACTIVE");
  const fees = model.feeTypes.filter(inActiveSchoolYear);
  const payments = model.payments.filter((item) => inActiveSchoolYear(item) && (!from || item.paidAt >= from) && (!to || item.paidAt <= to));
  const expenses = model.expenses.filter((item) => inActiveSchoolYear(item) && (!from || item.spentAt >= from) && (!to || item.spentAt <= to));
  const personnel = model.personnel.filter((item) => { const inactive = item.active === false || item.status === "inactive"; return isInternalPersonnel(item) && typeof item.schoolId === "string" && schoolIds.includes(item.schoolId) && (!personnelRole || item.role === personnelRole) && (!personnelStatus || (personnelStatus === "inactive" ? inactive : !inactive)) && `${item.name} ${item.email ?? ""} ${item.role}`.toLowerCase().includes(search.toLowerCase()); });
  const logs = model.auditLogs.filter((item) => { const authorized = user.role === "coordination_admin" ? (item.coordinationId === coordination.id || Boolean(item.schoolId && allSchoolIds.includes(item.schoolId))) : (item.subCoordinationId === user.subCoordinationId || Boolean(item.schoolId && allSchoolIds.includes(item.schoolId))); return authorized && (!drawerSchoolId || item.schoolId === drawerSchoolId) && `${item.action} ${item.actorName ?? ""} ${item.details ?? ""}`.toLowerCase().includes(search.toLowerCase()); }).sort((a, b) => activityTimestamp(b.createdAt) - activityTimestamp(a.createdAt));
  const visibleYearRows = yearRows.filter((row) => schoolIds.includes(row.schoolId));
  const financialGroups = groupCoordinationFinancialsByCurrency({ schools: scopedSchools, students, feeTypes: fees, payments, expenses });

  async function exportPdf(kind: Exclude<Drawer, "settings" | "subCoordinations">) {
    const contextSchool = schools.find((item) => item.id === drawerSchoolId) ?? schools[0]; if (!contextSchool) return;
    const context = drawerSchoolId ? contextSchool.name : "Toutes les écoles";
    const sections = kind === "fees" ? financialGroups.map((group) => pdfSection(`Types de frais — ${group.currency}`, pdfTable([{ header: "Type", render: (item) => item.name }, { header: "Attendu", render: (item) => formatCurrencyMoney(item.expected, group.currency) }, { header: "Payé", render: (item) => formatCurrencyMoney(item.paid, group.currency) }, { header: "Solde", render: (item) => formatCurrencyMoney(item.remaining, group.currency) }, { header: "%", render: (item) => `${item.rate}%` }], group.feeProgressRows, "Aucun type de frais applicable.")))
      : kind === "finance" ? financialGroups.flatMap((group) => [pdfSection(`Synthèse financière — ${group.currency}`, pdfTable([{ header: "Indicateur", render: (item) => item.label }, { header: "Montant", render: (item) => formatCurrencyMoney(item.value, group.currency) }], [{ label: "Attendu", value: group.expected }, { label: "Encaissé", value: group.paid }, { label: "Dépenses", value: group.expenses }, { label: "Reste", value: group.remaining }], "Aucune opération.")), pdfSection(`Paiements — ${group.currency}`, pdfTable([{ header: "École", render: (item) => schoolName(item.schoolId) }, { header: "Date", render: (item) => item.paidAt }, { header: "Montant", render: (item) => formatCurrencyMoney(item.amount, group.currency) }], group.payments, "Aucun paiement.")), pdfSection(`Dépenses — ${group.currency}`, pdfTable([{ header: "École", render: (item) => schoolName(item.schoolId) }, { header: "Date", render: (item) => item.spentAt }, { header: "Montant", render: (item) => formatCurrencyMoney(item.amount, group.currency) }], group.expenseRows, "Aucune dépense."))])
      : kind === "personnel" ? [pdfSection("Personnels", pdfTable([{ header: "École", render: (item) => schoolName(item.schoolId) }, { header: "Nom", render: (item) => item.name }, { header: "Fonction", render: (item) => roleLabel[item.role] ?? item.role }, { header: "Statut", render: (item) => item.active === false || item.status === "inactive" ? "Inactif" : "Actif" }], personnel, "Aucun personnel."))]
      : kind === "years" ? [pdfSection("Années scolaires", pdfTable([{ header: "École", render: (item) => item.schoolName }, { header: "Année active", render: (item) => item.activeYear?.name ?? "Aucune" }, { header: "Alignement", render: (item) => !referenceYear || item.activeYear?.name === referenceYear ? "Alignée" : "Année scolaire non alignée" }], visibleYearRows, "Aucune école."))]
      : [pdfSection("Historique", pdfTable([{ header: "Date", render: (item) => formatActivityDateTime(item.createdAt) }, { header: "École", render: (item) => schoolName(item.schoolId) }, { header: "Action", render: (item) => escapePdfHtml(item.action) }, { header: "Acteur", render: (item) => item.actorName ?? "—" }], logs, "Aucune activité."))];
    await renderAcadPdfPreview({ filename: `coordination-${kind}-${drawerSchoolId || "toutes"}.pdf`, title: `Coordination — ${kind}`, school: coordinationPdfInstitution(coordination, contextSchool), subtitle: context, sections });
  }

  async function saveSettings() { if (user.role !== "coordination_admin" || settingsBusy) return; setSettingsBusy(true); setError(""); try { await updateCoordinationSettings(settingsForm); } catch (cause) { setError(cause instanceof Error ? cause.message : "Enregistrement impossible."); } finally { setSettingsBusy(false); } }
  async function mutateYears(action: "close" | "open") { if (user.role !== "coordination_admin") { setError("La gouvernance annuelle reste réservée au Coordinateur principal."); return; } setYearBusy(true); try { const response = action === "close" ? await closeCoordinationSchoolYears() : await openCoordinationSchoolYears({ name: yearName, startsAt, endsAt }); setYearResults(response.results); } catch (cause) { setError(cause instanceof Error ? cause.message : "Opération impossible."); } finally { setYearBusy(false); } }

  const items = [["fees", "Types de frais", BookOpen], ["finance", "Rapport financier", Landmark], ["personnel", "Personnels", UsersRound], ["years", "Année scolaire", CalendarRange], ["settings", "Paramètres coordination", Settings], ["history", "Historique", FileClock], ...(user.role === "coordination_admin" ? [["subCoordinations", "Sous-coordinations", Network] as const] : [])] as const;
  function settingsContent(): ReactNode { if (subCoordination || user.role !== "coordination_admin") return <><p className="break-words"><b>{subCoordination ? "Circonscription" : "Coordination"} :</b> {subCoordination?.circumscription ?? coordination.name}</p>{subCoordination && <><p className="break-words"><b>Sous-coordinateur :</b> {user.name}</p><p><b>Statut :</b> {subCoordination.active ? "Actif" : "Archivé"}</p></>}<p><b>Écoles attribuées :</b> {schools.length}</p><p className="rounded bg-slate-50 p-3">Ces paramètres sont disponibles en lecture seule.</p></>; return <><label className="grid min-w-0 gap-1 font-semibold">Nom<input className="input min-w-0 w-full" value={settingsForm.name} onChange={(event) => setSettingsForm({ ...settingsForm, name: event.target.value })} disabled={settingsBusy} /></label><label className="grid min-w-0 gap-1 font-semibold">Sigle / code<input className="input min-w-0 w-full" value={settingsForm.code} onChange={(event) => setSettingsForm({ ...settingsForm, code: event.target.value })} disabled={settingsBusy} /></label><label className="grid min-w-0 gap-1 font-semibold">Téléphone<input className="input min-w-0 w-full" value={settingsForm.phone} onChange={(event) => setSettingsForm({ ...settingsForm, phone: event.target.value })} disabled={settingsBusy} /></label><label className="grid min-w-0 gap-1 font-semibold">E-mail<input className="input min-w-0 w-full" type="email" value={settingsForm.email} onChange={(event) => setSettingsForm({ ...settingsForm, email: event.target.value })} disabled={settingsBusy} /></label><label className="grid min-w-0 gap-1 font-semibold">Adresse<input className="input min-w-0 w-full" value={settingsForm.address} onChange={(event) => setSettingsForm({ ...settingsForm, address: event.target.value })} disabled={settingsBusy} /></label><ImageUploadField label="Photo / Logo de la Coordination" value={settingsForm.logoUrl} onChange={(logoUrl) => setSettingsForm({ ...settingsForm, logoUrl })} maxWidth={700} maxBytes={250 * 1024} disabled={settingsBusy} previewFit="contain" /><p className="break-words"><b>Coordinateur principal :</b> {principalCoordinatorName || "Non renseigné"}</p><p><b>Écoles :</b> {schools.length} (lecture seule)</p><button type="button" className="primary-button w-full justify-center sm:w-auto" disabled={settingsBusy || !settingsForm.name.trim()} onClick={() => void saveSettings()}>{settingsBusy ? "Enregistrement…" : "Enregistrer les paramètres"}</button><p className="rounded bg-slate-50 p-3">Le rattachement des écoles reste réservé au Super Administrateur.</p></>; }
  function drawerContent(): ReactNode {
    if (drawer === "fees") return <><SchoolPdfControls schools={schools} schoolId={drawerSchoolId} user={user} onSchoolChange={setDrawerSchoolId} onExport={() => void exportPdf("fees")}/>{financialGroups.map((group) => <section key={group.currency} className="grid gap-2 rounded border border-slate-200 p-3"><h3 className="font-bold text-ink">Types de frais — {group.currency}</h3><ReadTable headers={["Type", "Attendu", "Payé", "Solde", "%"]} rows={group.feeProgressRows.map((item) => [item.name, formatCurrencyMoney(item.expected, group.currency), formatCurrencyMoney(item.paid, group.currency), formatCurrencyMoney(item.remaining, group.currency), `${item.rate}%`])} /></section>)}</>;
    if (drawer === "finance") return <><SchoolPdfControls schools={schools} schoolId={drawerSchoolId} user={user} onSchoolChange={setDrawerSchoolId} onExport={() => void exportPdf("finance")}/><div className="grid gap-2 sm:grid-cols-2"><input className="input min-w-0 w-full" aria-label="Date de début" type="date" value={from} onChange={(event) => setFrom(event.target.value)} /><input className="input min-w-0 w-full" aria-label="Date de fin" type="date" value={to} onChange={(event) => setTo(event.target.value)} /></div>{financialGroups.map((group) => <section key={group.currency} className="grid gap-3 rounded border border-slate-200 p-3"><h3 className="font-bold text-ink">Synthèse financière — {group.currency}</h3><ReadTable headers={["Indicateur", "Montant"]} rows={[["Attendu", formatCurrencyMoney(group.expected, group.currency)], ["Encaissé", formatCurrencyMoney(group.paid, group.currency)], ["Dépenses", formatCurrencyMoney(group.expenses, group.currency)], ["Reste", formatCurrencyMoney(group.remaining, group.currency)], ["Recouvrement", `${group.recoveryRate}%`]]} /><h4 className="font-semibold text-ink">Paiements — {group.currency}</h4><ReadTable headers={["École", "Date", "Montant"]} rows={group.payments.map((item) => [schoolName(item.schoolId), item.paidAt, formatCurrencyMoney(item.amount, group.currency)])} /><h4 className="font-semibold text-ink">Dépenses — {group.currency}</h4><ReadTable headers={["École", "Date", "Montant"]} rows={group.expenseRows.map((item) => [schoolName(item.schoolId), item.spentAt, formatCurrencyMoney(item.amount, group.currency)])} /></section>)}</>;
    if (drawer === "personnel") return <><SchoolPdfControls schools={schools} schoolId={drawerSchoolId} user={user} onSchoolChange={setDrawerSchoolId} onExport={() => void exportPdf("personnel")}/><div className="grid gap-2 sm:grid-cols-3"><input className="input" placeholder="Rechercher" value={search} onChange={(event) => setSearch(event.target.value)} /><select className="input" aria-label="Filtrer par rôle" value={personnelRole} onChange={(event) => setPersonnelRole(event.target.value)}><option value="">Tous rôles</option>{INTERNAL_PERSONNEL_ROLES.map((role) => <option key={role} value={role}>{roleLabel[role]}</option>)}</select><select className="input" aria-label="Filtrer par statut" value={personnelStatus} onChange={(event) => setPersonnelStatus(event.target.value)}><option value="">Tous statuts</option><option value="active">Actifs</option><option value="inactive">Inactifs</option></select></div><ReadTable headers={["École", "Nom", "Fonction", "Statut"]} rows={personnel.map((item) => [schoolName(item.schoolId), <button type="button" className="text-left font-semibold text-blue-700 hover:underline" onClick={() => setSelectedPersonnel(item)}>{item.name}</button>, roleLabel[item.role] ?? item.role, item.active === false || item.status === "inactive" ? "Inactif" : "Actif"])} /></>;
    if (drawer === "years") return <><p className="rounded bg-blue-50 p-3 text-sm">Année de référence : <b>{referenceYear ?? "Non définie"}</b></p><button className="pdf-export-button w-full sm:w-auto" type="button" onClick={() => void exportPdf("years")}>Exporter PDF</button><ReadTable headers={["École", "Année active", "Alignement"]} rows={visibleYearRows.map((item) => [item.schoolName, item.activeYear?.name ?? "Aucune", !referenceYear || item.activeYear?.name === referenceYear ? "Alignée" : "Année non alignée"])} />{yearResults.length > 0 && <ReadTable headers={["École", "Résultat", "Motif"]} rows={yearResults.map((item) => [schoolName(item.schoolId), item.status, item.reason ?? "—"])} />}{user.role === "coordination_admin" ? <><button className="secondary-button w-full justify-center" disabled={yearBusy} type="button" onClick={() => void mutateYears("close")}>Clôturer les années prêtes</button><div className="grid min-w-0 gap-2 rounded border p-3"><input className="input min-w-0 w-full" placeholder="2027-2028" value={yearName} onChange={(event) => setYearName(event.target.value)} /><input className="input min-w-0 w-full" type="date" value={startsAt} onChange={(event) => setStartsAt(event.target.value)} /><input className="input min-w-0 w-full" type="date" value={endsAt} onChange={(event) => setEndsAt(event.target.value)} /><button className="primary-button w-full justify-center" disabled={yearBusy || !yearName || !startsAt || !endsAt} type="button" onClick={() => void mutateYears("open")}>Ouvrir la nouvelle année</button></div></> : <p className="rounded border border-blue-100 bg-blue-50 p-3 text-sm">Consultation uniquement. L’ouverture et la clôture restent réservées au Coordinateur principal.</p>}</>;
    if (drawer === "settings") return <div className="grid gap-3 text-sm">{settingsContent()}</div>;
    if (drawer === "history") return <><SchoolPdfControls schools={schools} schoolId={drawerSchoolId} user={user} onSchoolChange={setDrawerSchoolId} onExport={() => void exportPdf("history")}/><input className="input" placeholder="Rechercher" value={search} onChange={(event) => setSearch(event.target.value)} /><ReadTable headers={["Date", "École", "Action", "Acteur"]} rows={logs.map((item) => [formatActivityDateTime(item.createdAt), schoolName(item.schoolId), item.action, item.actorName ?? "—"])} /></>;
    return user.role === "coordination_admin" ? <SubCoordinationManagement coordination={coordination} schools={schools} currentUser={user} /> : null;
  }
  return <section className="grid min-w-0 gap-3">{items.map(([id, label, Icon]) => <button key={id} type="button" onClick={() => { setDrawerSchoolId(selectedSchoolId); setDrawer(id); setSearch(""); setSelectedPersonnel(undefined); }} className="min-w-0 rounded border border-slate-200 bg-white p-4 text-left shadow-sm transition hover:border-mint"><div className="flex min-w-0 items-center gap-3"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded bg-slate-100 text-ink"><Icon className="h-5 w-5"/></div><span className="break-words font-bold text-ink">{label}</span></div></button>)}<div className="mt-2 border-t border-slate-200 pt-4"><LogoutButton onClick={onLogout}/></div>{drawer && <AdminDrawer width={drawer === "settings" ? "default" : "wide"} title={items.find(([id]) => id === drawer)?.[1] ?? "Coordination"} closeLabel="Fermer" onClose={() => { setDrawer(null); setSelectedPersonnel(undefined); }}>{error && <p role="alert" className="rounded bg-red-50 p-3 text-sm text-red-700">{error}</p>}{loading && <p className="text-sm text-slate-500">Chargement…</p>}{drawerContent()}</AdminDrawer>}{selectedPersonnel && <AdminDrawer width="wide" title={`Personnel — ${selectedPersonnel.name}`} closeLabel="Fermer la fiche Personnel" onClose={() => setSelectedPersonnel(undefined)}><button type="button" className="primary-button w-full justify-center sm:w-auto" disabled={!personnelProfileReady} onClick={() => { const school = schools.find((item) => item.id === selectedPersonnel.schoolId); if (school) void printPersonnelProfilePdf(coordinationPdfInstitution(coordination, school), selectedPersonnel, selectedPersonnelProfile, new Date(), { personnelSchoolName: school.name }); }}><Printer className="h-4 w-4"/> Imprimer</button>{!personnelProfileReady ? <p role="status" className="py-4 text-center text-sm text-slate-500">Chargement de la fiche administrative…</p> : <PersonnelProfileReadOnly personnel={selectedPersonnel} profile={selectedPersonnelProfile} schoolName={schoolName(selectedPersonnel.schoolId)}/>}</AdminDrawer>}</section>;
}

function SchoolPdfControls({ schools, schoolId, user, onSchoolChange, onExport }: { schools: School[]; schoolId: string; user: AppUser; onSchoolChange: (schoolId: string) => void; onExport: () => void }) { return <div className="grid min-w-0 gap-2 sm:grid-cols-[minmax(0,1fr)_auto]"><select className="input min-w-0" aria-label="Filtrer le Drawer par école" value={schoolId} onChange={(event) => onSchoolChange(event.target.value)}><option value="">{user.role === "sub_coordination_admin" ? "Toutes mes écoles" : "Toutes les écoles"}</option>{schools.map((school) => <option key={school.id} value={school.id}>{school.name}</option>)}</select><button className="pdf-export-button min-w-0" type="button" onClick={onExport}>Exporter PDF</button></div>; }
function ReadTable({ headers, rows }: { headers: string[]; rows: ReactNode[][] }) { return <div className="max-w-full overflow-x-auto"><table className="w-full min-w-[560px] text-left text-sm"><thead><tr className="border-b">{headers.map((header) => <th key={header} className="p-2">{header}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr key={index} className="border-b">{row.map((cell, cellIndex) => <td key={cellIndex} className="break-words p-2">{cell}</td>)}</tr>)}</tbody></table>{rows.length === 0 && <p className="p-4 text-sm text-slate-500">Aucune donnée.</p>}</div>; }
