import { describe,expect,it } from "vitest";
import { hasMeaningfulStudyAiChange,resolveStudyEntity,reoptimizeStudySchedule,stabilityMetrics,validateStudyAiInterpretation,type StudyAiInterpretation } from "./studyAssistant";
import type { PedagogicalAssignment,SchedulePeriod,StudyClass,StudySubject,StudyTeacher,TimetableEntry } from "./studyTypes";
const teacher=(id:string,name:string):StudyTeacher=>({id,fullName:name,firstName:name,lastName:"Test",schoolId:"s",schoolYearId:"y",status:"active",createdAt:"",updatedAt:"",createdBy:"u"});
const schoolClass:StudyClass={id:"c",name:"6e A",schoolId:"s",schoolYearId:"y",active:true};const subject:StudySubject={id:"m",name:"Mathématiques",schoolId:"s",schoolYearId:"y",active:true,createdAt:"",updatedAt:"",createdBy:"u"};const assignment:PedagogicalAssignment={id:"a",schoolId:"s",schoolYearId:"y",teacherId:"t",classId:"c",subjectId:"m",weeklyPeriods:2,active:true,createdAt:"",updatedAt:"",createdBy:"u",updatedBy:"u"};const periods:SchedulePeriod[]=[1,2].map(order=>({id:`p${order}`,schoolId:"s",schoolYearId:"y",label:`P${order}`,startTime:`0${7+order}:00`,endTime:`0${8+order}:00`,order,type:"course",active:true,createdBy:"u",createdAt:"",updatedAt:""}));
const entry=(day:TimetableEntry["dayOfWeek"],periodId:string):TimetableEntry=>({id:`${day}-${periodId}`,scheduleId:"v1",schoolId:"s",schoolYearId:"y",assignmentId:"a",teacherId:"t",classId:"c",subjectId:"m",dayOfWeek:day,periodId,roomId:null,createdAt:"",updatedAt:""});
const interpretation=(overrides:Partial<StudyAiInterpretation>={}):StudyAiInterpretation=>({intent:"REOPTIMIZE_TEACHER",explanation:"",entityType:"teacher",entityQuery:"Kabeya",constraints:[],preferences:[{type:"MINIMIZE_CHANGES",weight:10}],requiresConfirmation:true,clarificationOptions:[],...overrides});
describe("Study assistant domain",()=>{
 it("résout une entité exacte et refuse inconnue",()=>{const data={teachers:[teacher("t","M. Kabeya")],classes:[schoolClass],subjects:[subject]};expect(resolveStudyEntity(interpretation(),data).status).toBe("resolved");expect(resolveStudyEntity(interpretation({entityQuery:"Inconnu"}),data).status).toBe("unknown")});
 it("demande clarification sur homonymes",()=>expect(resolveStudyEntity(interpretation(),{teachers:[teacher("t1","Kabeya Jean"),teacher("t2","Kabeya Paul")],classes:[],subjects:[]}).status).toBe("ambiguous"));
 it("calcule un score déterministe",()=>{const ten=Array.from({length:10},(_,i)=>entry(i<5?"monday":"tuesday",`p${i}`));expect(stabilityMetrics(ten,ten).stabilityScore).toBe(100);expect(stabilityMetrics(ten,[...ten.slice(0,9),{...ten[9],dayOfWeek:"friday"}]).stabilityScore).toBe(90)});
 it("réoptimise sans mercredi et conserve le volume",()=>{const baseline=[entry("wednesday","p1"),entry("tuesday","p1")];const result=reoptimizeStudySchedule({problem:{schoolId:"s",schoolYearId:"y",teachers:[teacher("t","Kabeya")],classes:[schoolClass],subjects:[subject],assignments:[assignment],availabilities:[],periods},baseline,entity:{type:"teacher",id:"t",label:"Kabeya"},interpretation:interpretation({constraints:[{type:"UNAVAILABLE_DAY",dayOfWeek:"wednesday",time:""}]})});expect(result.success).toBe(true);expect(result.entries).toHaveLength(2);expect(result.entries.some(x=>x.dayOfWeek==="wednesday")).toBe(false);expect(result.report?.valid).toBe(true)});
 it("normalise un jour français fourni par OpenAI avant le solveur",()=>{const result=reoptimizeStudySchedule({problem:{schoolId:"s",schoolYearId:"y",teachers:[teacher("t","Kabeya")],classes:[schoolClass],subjects:[subject],assignments:[{...assignment,weeklyPeriods:1}],availabilities:[],periods},baseline:[entry("monday","p1")],entity:{type:"teacher",id:"t",label:"Kabeya"},interpretation:interpretation({constraints:[{type:"UNAVAILABLE_DAY",dayOfWeek:"lundi",time:""}]})});expect(result.success).toBe(true);expect(result.entries).toHaveLength(1);expect(result.entries[0].dayOfWeek).not.toBe("monday");expect(result.metrics.moved).toBe(1)});
 it("refuse un brouillon inchangé lorsque la contrainte ne produit aucun déplacement",()=>{const constrained=interpretation({constraints:[{type:"UNAVAILABLE_DAY",dayOfWeek:"wednesday",time:""}]});expect(hasMeaningfulStudyAiChange(constrained,{moved:0,unchanged:1,stabilityScore:100})).toBe(false);expect(hasMeaningfulStudyAiChange(constrained,{moved:1,unchanged:0,stabilityScore:0})).toBe(true)});
 it("reproduit le scénario Staging et refuse une version DRAFT à 100 % inchangée",()=>{const constrained=interpretation({constraints:[{type:"UNAVAILABLE_DAY",dayOfWeek:"wednesday",time:""}]});const result=reoptimizeStudySchedule({problem:{schoolId:"s",schoolYearId:"y",teachers:[teacher("t","Kabeya")],classes:[schoolClass],subjects:[subject],assignments:[{...assignment,weeklyPeriods:1}],availabilities:[],periods},baseline:[entry("monday","p1")],entity:{type:"teacher",id:"t",label:"Kabeya"},interpretation:constrained});expect(result.success).toBe(false);expect(result.entries).toEqual([]);expect(result.failures[0].reason).toContain("Aucun brouillon")});
 it("explique un cas impossible sans résultat partiel",()=>{const impossible={...assignment,weeklyPeriods:20};const result=reoptimizeStudySchedule({problem:{schoolId:"s",schoolYearId:"y",teachers:[teacher("t","Kabeya")],classes:[schoolClass],subjects:[subject],assignments:[impossible],availabilities:[],periods:[periods[0]],maxSameAssignmentPeriodsPerDay:2},baseline:[],entity:{type:"teacher",id:"t",label:"Kabeya"},interpretation:interpretation(),timeoutMs:100});expect(result.success).toBe(false);expect(result.entries).toEqual([]);expect(result.failures[0].reason).toBeTruthy()});
 it("rejette une réponse mal formée",()=>expect(()=>validateStudyAiInterpretation({intent:"DELETE"})).toThrow());
});
