
import { useMemo, useState } from "react";
import { Bot, Send, Sparkles } from "lucide-react";
import { AdminDrawer } from "../../components/ui";
import type { AppUser, School, SchoolYear } from "../../types";
import { requestStudyAi } from "../../services/studyAi";
import { getActiveSchedulePersonnel } from "./studyPersonnel";
import { loadSchoolAiAssistantSetting, schoolAiUsageThisMonth } from "../../services/schoolAiAssistant";
import { resolveStudyEntity, reoptimizeStudySchedule, validateStudyAiInterpretation, type ResolvedEntity, type StudyAiInterpretation } from "./studyAssistant";
import { saveGeneratedTimetable } from "./studyService";
import type { useStudyData } from "./useStudyData";
const suggestions=["Résume l’horaire actuel","Explique les conflits","Réorganise un enseignant en minimisant les changements","Vérifie la faisabilité","Réduis les trous d’une classe","Répartis une matière sur la semaine"];
type Message={author:"user"|"assistant";text:string};
export function StudyAiAssistant({user,school,year,data}:{user:AppUser;school:School;year:SchoolYear;data:ReturnType<typeof useStudyData>}){const[open,setOpen]=useState(false),[prompt,setPrompt]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[messages,setMessages]=useState<Message[]>([]),[interpretation,setInterpretation]=useState<StudyAiInterpretation>(),[entity,setEntity]=useState<ResolvedEntity>(),[result,setResult]=useState<{stabilityScore:number;moved:number;unchanged:number;version:number}>();const source=useMemo(()=>[...data.timetables].sort((a,b)=>b.version-a.version).find(x=>x.activePublished)||[...data.timetables].sort((a,b)=>b.version-a.version)[0],[data.timetables]);const sourceEntries=useMemo(()=>source?data.timetableEntries.filter(x=>x.scheduleId===source.id):[],[data.timetableEntries,source]);const usage=schoolAiUsageThisMonth(school.aiAssistant);
async function send(){if(!prompt.trim()||busy)return;setBusy(true);setError("");setResult(undefined);const value=prompt.trim();setMessages(x=>[...x,{author:"user",text:value}]);try{const setting=await loadSchoolAiAssistantSetting(school.id);if(setting?.enabled!==true)throw new Error("L’Assistant IA n’est pas activé pour cet établissement.");const response=validateStudyAiInterpretation(await requestStudyAi(user,{schoolId:school.id,schoolYearId:year.id,prompt:value,context:{sourceScheduleId:source?.id??"",sourceStatus:source?.status??"NONE",entryCount:sourceEntries.length,teachers:data.teachers.map(x=>x.fullName),classes:data.classes.map(x=>x.name),subjects:data.subjects.map(x=>x.name),rooms:data.rooms.filter(x=>x.active).map(x=>x.name)}}));const resolved=resolveStudyEntity(response,data);if(resolved.status==="resolved")setEntity(resolved.entity);else setEntity(undefined);let text=response.explanation;if(resolved.status==="ambiguous")text=`Je n’ai pas compris précisément l’entité. Précisez parmi : ${resolved.options.map(x=>x.label).join(", ")}.`;if(resolved.status==="unknown"&&response.entityType!=="none")text="L’entité demandée n’existe pas dans cet établissement.";setInterpretation(resolved.status==="resolved"||resolved.status==="none"?response:{...response,intent:"NEEDS_CLARIFICATION",requiresConfirmation:false,clarificationOptions:resolved.options.map(x=>x.label)});setMessages(x=>[...x,{author:"assistant",text}]);setPrompt("");}catch(cause){setError(cause instanceof Error?cause.message:"Assistant IA indisponible.");}finally{setBusy(false)}}
async function apply(){if(!interpretation?.requiresConfirmation||!source||busy)return;setBusy(true);setError("");try{const schedulePersonnel=getActiveSchedulePersonnel(data.teachers,data.assignments);const problem={schoolId:school.id,schoolYearId:year.id,teachers:schedulePersonnel.teachers,subjects:data.subjects,classes:data.classes,assignments:schedulePersonnel.assignments,availabilities:data.availabilities,periods:data.periods,maxSameAssignmentPeriodsPerDay:2};const optimized=reoptimizeStudySchedule({problem,baseline:sourceEntries,interpretation,entity,timeoutMs:2000});if(!optimized.success)throw new Error(optimized.timedOut?"La réoptimisation a dépassé le délai sans modifier l’horaire.":`Cette demande est impossible avec les contraintes actuelles. ${optimized.failures.map(x=>x.reason).join(" ")}`);const version=Math.max(0,...data.timetables.map(x=>x.version))+1;await saveGeneratedTimetable({user,schoolId:school.id,schoolYearId:year.id,version,entries:optimized.entries,existing:data.timetables,metadata:{algorithm:"deterministic-backtracking",exploredBranches:0,durationMs:0,maxSameAssignmentPeriodsPerDay:2}});setResult({...optimized.metrics,version});setMessages(x=>[...x,{author:"assistant",text:`Une nouvelle version brouillon ${version} a été créée. ${optimized.metrics.moved} cours déplacé(s), ${optimized.metrics.unchanged} inchangé(s), stabilité ${optimized.metrics.stabilityScore}%.`}]);setInterpretation(undefined);}catch(cause){setError(cause instanceof Error?cause.message:"La réorganisation a échoué sans modifier l’horaire existant.");}finally{setBusy(false)}}
if(school.aiAssistant?.enabled!==true)return <section className="rounded border border-amber-200 bg-amber-50 p-4"><h2 className="font-bold">Assistant IA</h2><p className="text-sm text-amber-800">L’Assistant IA n’est pas activé pour votre établissement.</p></section>;return <><button type="button" className="flex w-full items-center gap-3 rounded border border-violet-200 bg-violet-50 p-4 text-left" onClick={()=>setOpen(true)}><Bot className="h-6 w-6 text-violet-700"/><span><b>Assistant IA</b><span className="block text-sm text-slate-600">Comprendre, expliquer et réoptimiser un horaire sans publication automatique.</span></span></button>{open&&<AdminDrawer title="Assistant IA" closeLabel="Fermer" onClose={()=>!busy&&setOpen(false)}><aside className="rounded border border-violet-200 bg-violet-50 p-3 text-sm">Quota mensuel : {usage.monthlyUsage}/{usage.monthlyLimit}. L’IA prépare uniquement des intentions et des brouillons à valider humainement.</aside><div className="grid w-full gap-2">{suggestions.map(x=><button key={x} className="secondary-button w-full justify-start text-xs" onClick={()=>setPrompt(x)}><Sparkles className="h-3 w-3"/>{x}</button>)}</div><div className="grid max-h-72 gap-2 overflow-y-auto">{messages.map((m,i)=><article key={i} className={`rounded p-3 text-sm ${m.author==="user"?"ml-8 bg-blue-50":"mr-8 bg-slate-50"}`}><b>{m.author==="user"?"Vous":"Assistant"}</b><p>{m.text}</p></article>)}</div>{interpretation&&<section className="grid gap-2 rounded border p-3 text-sm"><h3 className="font-bold">Demande comprise</h3><p>Intention : {interpretation.intent}</p>{entity&&<p>Entité : {entity.label}</p>}<p>Contraintes : {interpretation.constraints.map(x=>x.type).join(", ")||"Aucune"}</p><p>Préférences : {interpretation.preferences.map(x=>`${x.type} (${x.weight})`).join(", ")||"Aucune"}</p>{interpretation.clarificationOptions.length>0&&<p>Clarification : {interpretation.clarificationOptions.join(", ")}</p>}{interpretation.requiresConfirmation&&<div className="grid grid-cols-2 gap-2"><button className="secondary-button justify-center" disabled={busy} onClick={()=>setInterpretation(undefined)}>Annuler</button><button className="primary-button justify-center" disabled={busy} onClick={()=>void apply()}>{busy?"Réoptimisation…":"Appliquer et créer un DRAFT"}</button></div>}</section>}{result&&<p role="status" className="rounded border border-green-200 bg-green-50 p-3 text-sm">Version {result.version} DRAFT créée · stabilité {result.stabilityScore}%.</p>}{error&&<p role="alert" className="rounded border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</p>}<label className="grid gap-1 text-sm">Votre demande<textarea className="input min-h-24" value={prompt} onChange={e=>setPrompt(e.target.value)} maxLength={2000}/></label><button className="primary-button w-full justify-center" disabled={busy||!prompt.trim()||usage.limitReached} onClick={()=>void send()}><Send className="h-4 w-4"/>{busy?"Analyse…":"Envoyer"}</button></AdminDrawer>}</>}
