import { useState } from "react";
import type { AppUser, School, SchoolYear } from "../../types";
import { saveStudyRoom, setStudyRoomActive } from "./studyService";
import type { StudyRoom } from "./studyTypes";
import type { useStudyData } from "./useStudyData";

export function StudyRoomsModule({ user, school, year, data }: { user: AppUser; school: School; year: SchoolYear; data: ReturnType<typeof useStudyData> }) {
  const [editing, setEditing] = useState<StudyRoom>(); const [editorOpen, setEditorOpen] = useState(false); const [name, setName] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  function edit(room?: StudyRoom) { setEditing(room); setName(room?.name ?? ""); setError(""); setEditorOpen(true); }
  async function save() { setBusy(true); setError(""); try { await saveStudyRoom({ user, schoolId: school.id, schoolYearId: year.id, room: editing, name }); setEditorOpen(false); setEditing(undefined); setName(""); } catch (cause) { setError(cause instanceof Error ? cause.message : "Enregistrement impossible."); } finally { setBusy(false); } }
  return <section className="grid gap-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-xl font-bold">Salles</h2><p className="text-sm text-slate-600">Salles utilisables par le moteur d’horaires.</p></div><button className="primary-button justify-center" onClick={() => edit()}>Ajouter une salle</button></div><div className="grid gap-2">{data.rooms.map((room) => <article key={room.id} className="grid gap-3 rounded border bg-white p-3 sm:grid-cols-[minmax(0,1fr)_auto] sm:items-center"><span className="break-words"><b>{room.name}</b> · {room.active ? "Active" : "Inactive"}</span><div className="flex flex-wrap gap-2"><button className="secondary-button" onClick={() => edit(room)}>Modifier</button>{room.active && <button className="secondary-button" onClick={() => void setStudyRoomActive(user, room, false)}>Désactiver</button>}</div></article>)}</div>{editorOpen && <div className="grid gap-2 rounded bg-slate-50 p-3"><input className="input" placeholder="Nom / Libellé" value={name} onChange={(event) => setName(event.target.value)} />{error && <p role="alert" className="text-red-700">{error}</p>}<div className="grid grid-cols-2 gap-2"><button className="secondary-button justify-center" disabled={busy} onClick={() => setEditorOpen(false)}>Annuler</button><button className="primary-button justify-center" disabled={busy || !name.trim()} onClick={() => void save()}>{busy ? "Enregistrement…" : "Enregistrer"}</button></div></div>}</section>;
}
