import fs from "node:fs";
import { describe, expect, it } from "vitest";
describe("portail Direction des études responsive", () => {
  const portal = fs.readFileSync("src/modules/studies/StudyDirectorPortal.tsx", "utf8"); const schedules = fs.readFileSync("src/modules/studies/StudySchedulesModule.tsx", "utf8"); const teachers = fs.readFileSync("src/modules/studies/StudyTeachersModule.tsx", "utf8");
  it("affiche trois cartes par rangée au desktop et un menu vertical", () => { expect(portal).toContain("lg:grid-cols-3"); for (const label of ["Historique des versions", "Périodes & tranches horaires"]) expect(portal).toContain(label); expect(portal).toContain('activeTab === "menu" && <section className="grid gap-3"><StudyAiAssistant'); expect(portal).not.toContain('setDrawer("rooms")'); });
  it("retire l’historique de l’onglet et exporte le filtre courant", () => { expect(schedules).not.toContain("StudyScheduleHistory"); expect(schedules).toContain("Exporter PDF"); expect(schedules).toContain("entries: filtered"); });
  it("utilise la même liste de classes avec élèves pour classe et titulaire", () => { expect(teachers).toContain("Titulaire de la classe (facultatif)"); expect(teachers).toContain("Choisir classe"); expect(teachers).toContain("classesWithEnrolledStudents(classes, students, school.id, year.id)"); expect(teachers.match(/assignmentClasses\.map/g)).toHaveLength(2); expect(teachers).toContain("Aucune classe disponible."); expect(teachers).not.toContain("Salle préférée (facultatif)"); });
  it("fusionne les filtres d’horaire et conserve l’ordre responsive", () => { expect(schedules).toContain('aria-label="Mode d’affichage"'); expect(schedules).toContain('<option value="class">Par classe</option>'); expect(schedules).toContain('<option value="teacher">Par enseignant</option>'); expect(schedules).not.toContain("Par salle"); expect(schedules).toContain("lg:flex-nowrap"); expect(schedules.indexOf("Générer automatiquement")).toBeLessThan(schedules.indexOf("Exporter PDF")); });
});
