import fs from "node:fs";
import { describe, expect, it } from "vitest";
describe("portail Direction des études responsive", () => {
  const portal = fs.readFileSync("src/modules/studies/StudyDirectorPortal.tsx", "utf8"); const schedules = fs.readFileSync("src/modules/studies/StudySchedulesModule.tsx", "utf8"); const teachers = fs.readFileSync("src/modules/studies/StudyTeachersModule.tsx", "utf8");
  it("affiche trois cartes par rangée au desktop et un menu vertical", () => { expect(portal).toContain("lg:grid-cols-3"); for (const label of ["Historique des versions", "Historique", "Périodes & tranches horaires"]) expect(portal).toContain(label); expect(portal).toContain('activeTab === "menu" && <section className="grid gap-3"><StudyAiAssistant'); expect(portal).toContain('setDrawer("activity-history")'); expect(portal).not.toContain('setDrawer("rooms")'); });
  it("retire l’historique de l’onglet et exporte le filtre courant", () => { expect(schedules).not.toContain("StudyScheduleHistory"); expect(schedules).toContain("Exporter PDF"); expect(schedules).toContain("entries: filtered"); });
  it("utilise la même liste de classes avec élèves pour classe et titulaires multiples", () => { expect(teachers).toContain("Titulaire de la classe (facultatif)"); expect(teachers).toContain("classesWithEnrolledStudents(classes, students, school.id, year.id)"); expect(teachers).toContain("options={assignmentClasses.map"); expect(teachers).toContain("values={titularClassIds}"); expect(teachers).toContain("assignmentClasses.filter((item) => classIds.includes(item.id))"); expect(teachers).toContain('placeholder="Aucune classe sélectionnée"'); expect(teachers).not.toContain("Salle préférée (facultatif)"); });

  it("affiche les classes de titularité dans la liste principale", () => { expect(teachers).toContain('"Titulaire de la classe"'); expect(teachers).toContain("titularClasses"); expect(teachers).toContain("colSpan={7}"); });
  it("fusionne les filtres d’horaire et ajoute le mode par jour", () => { expect(schedules).toContain('aria-label="Mode d’affichage"'); expect(schedules).toContain('<option value="class">Par classe</option>'); expect(schedules).toContain('<option value="teacher">Par enseignant</option>'); expect(schedules).toContain('<option value="day">Par jour</option>'); expect(schedules).not.toContain("Par salle"); expect(schedules).toContain("lg:flex-nowrap"); expect(schedules.indexOf("Générer automatiquement")).toBeLessThan(schedules.indexOf("Exporter PDF")); });
  it("affiche les libellés métier et ignore les brouillons partiellement persistés", () => { expect(schedules).toContain("currentStudyTimetable(ordered)"); expect(schedules).toContain("studyDayLabel(item.dayOfWeek)"); expect(schedules).toContain("schedulePeriodLabel(item.periodId, data.periods)"); expect(schedules).toContain("periods: data.periods"); expect(schedules).not.toContain('>{item.dayOfWeek}</td>'); expect(schedules).not.toContain('>{item.periodId}</td>'); });
  it("ordonne le tableau pour l’affichage et retire uniquement la colonne Salle", () => { expect(schedules).toContain("sortTimetableEntriesForDisplay("); expect(schedules).toContain('["Jour", "Période", "Classe", "Enseignant", "Matière"]'); expect(schedules).toContain("colSpan={5}"); expect(schedules).not.toContain('"Salle"].map'); expect(schedules).not.toContain("data.rooms.find((entry) => entry.id === item.roomId)"); expect(schedules).toContain("rooms: data.rooms"); });
  it("désactive une génération fraîche et propose les deux stratégies si elle devient obsolète", () => { expect(schedules).toContain("scheduleIsFresh"); expect(schedules).toContain("sourceFingerprint"); expect(schedules).toContain('title="Mettre à jour l’horaire"'); expect(schedules).toContain("Conserver l’horaire existant et intégrer uniquement les changements"); expect(schedules).toContain("Régénérer entièrement l’horaire"); expect(schedules).toContain("prepareIncrementalFixedEntries"); });
  it("ferme le dialogue avant de lancer la génération choisie", () => { expect(schedules).toContain('function chooseGeneration(mode: GenerationMode) { setUpdateChoiceOpen(false); void generate(mode); }'); expect(schedules).toContain('onClick={() => chooseGeneration("incremental")}'); expect(schedules).toContain('onClick={() => chooseGeneration("full")}'); });
  it("demande une confirmation forte avant la désactivation d’un cours", () => { expect(teachers).toContain("ASSIGNMENT_DEACTIVATION_CONFIRMATION"); expect(teachers).toContain("Confirmation de la désactivation du cours"); expect(teachers).toContain("assignmentDeactivationConfirmed(deactivationConfirmation)"); expect(teachers).not.toContain("onClick={() => void setPedagogicalAssignmentActive(user, item, false)}"); });
  it("configure les blocs consécutifs dans le formulaire existant sans champ texte libre", () => { expect(teachers).toContain("Organisation des périodes"); expect(teachers).toContain("Répartition normale"); expect(teachers).toContain("Blocs consécutifs"); expect(teachers).toContain("Ajouter un bloc"); expect(teachers).toContain("Supprimer le bloc"); expect(teachers).toContain("validateAssignmentSessionPattern"); expect(teachers).toContain("grid min-w-0 gap-2 sm:grid-cols"); });
});
