import { useState } from "react";
import type { AppUser, School, SchoolYear } from "../../types";
import { saveSchedulePeriod, setSchedulePeriodActive } from "./studyService";
import type { SchedulePeriod } from "./studyTypes";
import type { useStudyData } from "./useStudyData";

export function StudyPeriodsModule({ user, school, year, data }: { user: AppUser; school: School; year: SchoolYear; data: ReturnType<typeof useStudyData> }) {
  const [editing, setEditing] = useState<SchedulePeriod>(); const [editorOpen, setEditorOpen] = useState(false); const [label, setLabel] = useState(""); const [start, setStart] = useState(""); const [end, setEnd] = useState(""); const [order, setOrder] = useState("1"); const [type, setType] = useState<SchedulePeriod["type"]>("course"); const [error, setError] = useState("");
  const sorted = [...data.periods].sort((a, b) => a.order - b.order || a.startTime.localeCompare(b.startTime));
  function edit(item?: SchedulePeriod) { setEditing(item); setLabel(item?.label ?? ""); setStart(item?.startTime ?? ""); setEnd(item?.endTime ?? ""); setOrder(String(item?.order ?? sorted.length + 1)); setType(item?.type ?? "course"); setError(""); setEditorOpen(true); }
  async function save() { const now = new Date().toISOString(); const id = editing?.id ?? `${school.id}__${year.id}__${crypto.randomUUID()}`; try { await saveSchedulePeriod({ user, item: { id, schoolId: school.id, schoolYearId: year.id, label: label.trim(), startTime: start, endTime: end, order: Number(order), type, active: editing?.active ?? true, createdBy: editing?.createdBy ?? user.id, createdAt: editing?.createdAt ?? now, updatedAt: now }, existing: data.periods }); setEditorOpen(false); setEditing(undefined); setError(""); } catch (cause) { setError(cause instanceof Error ? cause.message : "Enregistrement impossible."); } }
  return <section className="grid gap-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-xl font-bold">Périodes & tranches horaires</h2><p className="text-sm text-slate-600">Cours, pauses et récréations de l’année active.</p></div><button className="primary-button justify-center" onClick={() => edit()}>Ajouter une période</button></div><div className="grid gap-2">{sorted.map((item) => <article className="grid gap-3 rounded border bg-white p-3 sm:grid-cols-[minmax(0,1fr)_auto] sm:items-center" key={item.id}><p className="break-words"><b>{item.label}</b> — {item.startTime} → {item.endTime} — {item.type === "course" ? "Cours" : item.type === "break" ? "Pause" : "Récréation"} — {item.active ? "Active" : "Inactive"}</p><div className="flex flex-wrap gap-2"><button className="secondary-button" onClick={() => edit(item)}>Modifier</button>{item.active && <button className="secondary-button" onClick={() => void setSchedulePeriodActive(user, item, false)}>Désactiver</button>}</div></article>)}</div>{editorOpen && <div className="grid gap-3 rounded border bg-white p-4"><input className="input" placeholder="Libellé" value={label} onChange={(event) => setLabel(event.target.value)} /><div className="grid gap-2 sm:grid-cols-2"><input className="input" aria-label="Heure de début" type="time" value={start} onChange={(event) => setStart(event.target.value)} /><input className="input" aria-label="Heure de fin" type="time" value={end} onChange={(event) => setEnd(event.target.value)} /></div><input className="input" aria-label="Ordre" type="number" min="1" value={order} onChange={(event) => setOrder(event.target.value)} /><select className="input" value={type} onChange={(event) => setType(event.target.value as SchedulePeriod["type"])}><option value="course">Cours</option><option value="break">Pause</option><option value="recess">Récréation</option></select>{error && <p role="alert" className="text-red-700">{error}</p>}<div className="grid grid-cols-2 gap-2"><button className="secondary-button justify-center" onClick={() => setEditorOpen(false)}>Annuler</button><button className="primary-button justify-center" onClick={() => void save()}>Enregistrer</button></div></div>}</section>;
}
