import type { SchedulePeriod, StudyDay, TeacherAvailability } from "./studyTypes";
export const STUDY_DAYS: StudyDay[]=["monday","tuesday","wednesday","thursday","friday","saturday"];
export const DAY_LABELS:Record<StudyDay,string>={monday:"Lundi",tuesday:"Mardi",wednesday:"Mercredi",thursday:"Jeudi",friday:"Vendredi",saturday:"Samedi"};
export const minutes=(value:string)=>{const [h,m]=value.split(":").map(Number);return h*60+m;};
export function validTimeRange(start?:string,end?:string){return Boolean(start&&end&&/^\d{2}:\d{2}$/.test(start)&&/^\d{2}:\d{2}$/.test(end)&&minutes(start)<minutes(end));}
export function overlaps(a:{startTime?:string;endTime?:string},b:{startTime?:string;endTime?:string}){return Boolean(a.startTime&&a.endTime&&b.startTime&&b.endTime&&minutes(a.startTime)<minutes(b.endTime)&&minutes(b.startTime)<minutes(a.endTime));}
export function detectAvailabilityConflicts(items:TeacherAvailability[]){return items.some((a,i)=>items.some((b,j)=>j>i&&a.teacherId===b.teacherId&&a.dayOfWeek===b.dayOfWeek&&a.active&&b.active&&(a.status==="rest"||b.status==="rest"||overlaps(a,b))));}
export function validateAvailabilityRanges(status:TeacherAvailability["status"],ranges:Array<{startTime:string;endTime:string}>){if(status==="rest"&&ranges.length)return "Un jour de repos ne peut pas contenir de plage horaire.";for(const range of ranges){if(!range.startTime||!range.endTime)return "Chaque plage doit comporter une heure de début et de fin.";if(!validTimeRange(range.startTime,range.endTime))return "L’heure de fin doit être postérieure à l’heure de début.";}for(let i=0;i<ranges.length;i+=1)for(let j=i+1;j<ranges.length;j+=1)if(ranges[i].startTime===ranges[j].startTime&&ranges[i].endTime===ranges[j].endTime)return "Une même plage ne peut pas être ajoutée deux fois.";else if(overlaps(ranges[i],ranges[j]))return "Deux plages de la même journée ne peuvent pas se chevaucher.";return "";}
export function phase3DashboardMetrics(items:TeacherAvailability[],periods:SchedulePeriod[]){const active=items.filter(x=>x.active);return{teachersWithUnavailability:new Set(active.filter(x=>x.status==="unavailable").map(x=>x.teacherId)).size,teachersWithRestDays:new Set(active.filter(x=>x.status==="rest").map(x=>x.teacherId)).size,activeCoursePeriods:periods.filter(x=>x.active&&x.type==="course").length,activeNonTeachingPeriods:periods.filter(x=>x.active&&x.type!=="course").length};}
export function isRestDay(teacherId:string,day:StudyDay,items:TeacherAvailability[]){return items.some(x=>x.teacherId===teacherId&&x.dayOfWeek===day&&x.active&&x.status==="rest");}
export function teacherAvailableAt(teacherId:string,day:StudyDay,period:SchedulePeriod,items:TeacherAvailability[]){const dayItems=items.filter(x=>x.teacherId===teacherId&&x.dayOfWeek===day&&x.active);if(dayItems.some(x=>x.status==="rest"))return false;const unavailable=dayItems.filter(x=>x.status==="unavailable");if(unavailable.some(x=>!x.startTime||overlaps(x,period)))return false;const available=dayItems.filter(x=>x.status==="available");return available.length===0||available.some(x=>!x.startTime||(minutes(x.startTime)<=minutes(period.startTime)&&minutes(x.endTime!)>=minutes(period.endTime)));}
export const getActiveCoursePeriods=(items:SchedulePeriod[])=>items.filter(x=>x.active&&x.type==="course").sort((a,b)=>a.order-b.order||minutes(a.startTime)-minutes(b.startTime));
export const getNonTeachingPeriods=(items:SchedulePeriod[])=>items.filter(x=>x.active&&x.type!=="course").sort((a,b)=>a.order-b.order||minutes(a.startTime)-minutes(b.startTime));
export function validatePeriod(candidate:SchedulePeriod,items:SchedulePeriod[],ignored?:string){if(!validTimeRange(candidate.startTime,candidate.endTime))return "L’heure de fin doit être postérieure à l’heure de début.";if(items.some(x=>x.id!==ignored&&x.active&&x.order===candidate.order))return "Cet ordre est déjà utilisé.";if(items.some(x=>x.id!==ignored&&x.active&&overlaps(x,candidate)))return "Cette tranche chevauche une période existante.";return "";}
