import type { PedagogicalAssignment, ScheduleValidationIssue, StudyClass, StudyDay, StudySubject, StudyTeacher, TimetableEntry } from "./studyTypes";
import type { ScheduleProblem } from "./scheduleValidation";
import { validateTimetable } from "./scheduleValidation";
import { DeterministicTimetableSolver } from "./timetableSolver";

export const STUDY_AI_INTENTS=["EXPLAIN_SCHEDULE","EXPLAIN_CONFLICT","REOPTIMIZE_TEACHER","REOPTIMIZE_CLASS","APPLY_AVAILABILITY_CONSTRAINT","PREFER_SUBJECT_TIME","MINIMIZE_CHANGES","SUMMARIZE_SCHEDULE","CHECK_FEASIBILITY","NEEDS_CLARIFICATION"] as const;
export type StudyAiIntent=typeof STUDY_AI_INTENTS[number];
export interface StudyAiInterpretation{intent:StudyAiIntent;explanation:string;entityType:"teacher"|"class"|"subject"|"room"|"none";entityQuery:string;constraints:Array<{type:"UNAVAILABLE_DAY"|"UNAVAILABLE_AFTER"|"PREFER_MORNING"|"REDUCE_GAPS"|"DISTRIBUTE_SUBJECT";dayOfWeek:string;time:string}>;preferences:Array<{type:"MINIMIZE_CHANGES"|"PREFER_MORNING"|"REDUCE_GAPS"|"DISTRIBUTE_SUBJECT";weight:number}>;requiresConfirmation:boolean;clarificationOptions:string[];requestId?:string}
export type ResolvedEntity={type:StudyAiInterpretation["entityType"];id:string;label:string};
const normalized=(value:string)=>value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/\b(m|mme|monsieur|madame)\b/g,"").replace(/[^a-z0-9]+/g," ").trim();
const studyDay=(value:string):StudyDay=>({lundi:"monday",mardi:"tuesday",mercredi:"wednesday",jeudi:"thursday",vendredi:"friday",samedi:"saturday",monday:"monday",tuesday:"tuesday",wednesday:"wednesday",thursday:"thursday",friday:"friday",saturday:"saturday"} as Record<string,StudyDay>)[normalized(value)]??value as StudyDay;
export function validateStudyAiInterpretation(value:unknown):StudyAiInterpretation{if(!value||typeof value!=="object")throw new Error("Réponse IA invalide.");const x=value as StudyAiInterpretation;if(!STUDY_AI_INTENTS.includes(x.intent)||!Array.isArray(x.constraints)||!Array.isArray(x.preferences)||!Array.isArray(x.clarificationOptions)||typeof x.explanation!=="string"||typeof x.requiresConfirmation!=="boolean")throw new Error("Réponse IA invalide.");return x;}
export function resolveStudyEntity(interpretation:StudyAiInterpretation,data:{teachers:StudyTeacher[];classes:StudyClass[];subjects:StudySubject[]}){if(interpretation.entityType==="none")return{status:"none" as const};const rows=interpretation.entityType==="teacher"?data.teachers.map(x=>({id:x.id,label:x.fullName})):interpretation.entityType==="class"?data.classes.map(x=>({id:x.id,label:x.name})):interpretation.entityType==="subject"?data.subjects.map(x=>({id:x.id,label:x.name})):[];const query=normalized(interpretation.entityQuery);const matches=rows.filter(x=>{const label=normalized(x.label);return label===query||label.includes(query)||query.includes(label)});return matches.length===1?{status:"resolved" as const,entity:{type:interpretation.entityType,id:matches[0].id,label:matches[0].label}}:matches.length>1?{status:"ambiguous" as const,options:matches}:{status:"unknown" as const,options:[]};}
export function stabilityMetrics(before:TimetableEntry[],after:TimetableEntry[]){const same=new Set(before.map(e=>`${e.assignmentId}|${e.dayOfWeek}|${e.periodId}|${e.roomId??""}`));const unchanged=after.filter(e=>same.has(`${e.assignmentId}|${e.dayOfWeek}|${e.periodId}|${e.roomId??""}`)).length;const total=Math.max(before.length,after.length);return{unchanged,moved:Math.max(0,total-unchanged),stabilityScore:total===0?100:Math.round(unchanged/total*100)};}
export function hasMeaningfulStudyAiChange(interpretation:StudyAiInterpretation,metrics:ReturnType<typeof stabilityMetrics>){return interpretation.constraints.length===0||metrics.moved>0;}
export function explainValidationIssue(issue:ScheduleValidationIssue,lookups:{teachers:StudyTeacher[];classes:StudyClass[];subjects:StudySubject[]}){const teacher=lookups.teachers.find(x=>x.id===issue.entityId)?.fullName;const prefix=teacher?`${teacher} : `:"";return`${prefix}${issue.message}${issue.day?` (${issue.day}${issue.periodId?`, ${issue.periodId}`:""})`:""}`;}
export function reoptimizeStudySchedule(input:{problem:ScheduleProblem;baseline:TimetableEntry[];interpretation:StudyAiInterpretation;entity?:ResolvedEntity;timeoutMs?:number}){const availability=[...input.problem.availabilities];const entity=input.entity;for(const constraint of input.interpretation.constraints){if(entity?.type!=="teacher")continue;const dayOfWeek=studyDay(constraint.dayOfWeek);if(constraint.type==="UNAVAILABLE_DAY")availability.push({id:`ai-${entity.id}-${dayOfWeek}`,schoolId:input.problem.schoolId,schoolYearId:input.problem.schoolYearId,teacherId:entity.id,dayOfWeek,status:"rest",active:true,createdBy:"ai-simulation",createdAt:"",updatedAt:""});if(constraint.type==="UNAVAILABLE_AFTER")availability.push({id:`ai-${entity.id}-${dayOfWeek}`,schoolId:input.problem.schoolId,schoolYearId:input.problem.schoolYearId,teacherId:entity.id,dayOfWeek,status:"unavailable",startTime:constraint.time,endTime:"23:59",active:true,createdBy:"ai-simulation",createdAt:"",updatedAt:""});}
  const preferredMorning=input.interpretation.preferences.some(x=>x.type==="PREFER_MORNING")||input.interpretation.constraints.some(x=>x.type==="PREFER_MORNING");const targetAssignments=input.problem.assignments.filter((x:PedagogicalAssignment)=>entity?.type==="teacher"?x.teacherId===entity.id:entity?.type==="class"?x.classId===entity.id:entity?.type==="subject"?x.subjectId===entity.id:false).map(x=>x.id);const problem={...input.problem,availabilities:availability};const solved=new DeterministicTimetableSolver().solve(problem,{timeoutMs:input.timeoutMs??2000,baselineEntries:input.baseline,preferredMorningAssignmentIds:preferredMorning?targetAssignments:[]});if(!solved.success)return{success:false,entries:[],metrics:stabilityMetrics(input.baseline,[]),failures:solved.failures,timedOut:solved.statistics.timedOut};const report=validateTimetable(problem,solved.entries);const metrics=stabilityMetrics(input.baseline,solved.entries);if(report.valid&&!hasMeaningfulStudyAiChange(input.interpretation,metrics))return{success:false,entries:[],metrics,failures:[{reason:"Aucune modification applicable n’a été trouvée. Aucun brouillon n’a été créé."}],timedOut:false,report};return{success:report.valid,entries:solved.entries,metrics,failures:report.errors.map(x=>({reason:x.message})),timedOut:false,report};}
