import { getActiveCoursePeriods, STUDY_DAYS, teacherAvailableAt } from "./studySchedule";
import { adjacentCoursePeriods, validateTimetable, type ScheduleProblem } from "./scheduleValidation";
import type { PedagogicalAssignment, StudyDay, TimetableEntry } from "./studyTypes";

export const DEFAULT_MAX_SAME_ASSIGNMENT_PERIODS_PER_DAY=2;
export interface SolverFailure { assignmentId:string; teacherId:string; classId:string; subjectId:string; required:number; availableCapacity:number; reason:string; }
export interface SolverResult { success:boolean; entries:TimetableEntry[]; failures:SolverFailure[]; statistics:{exploredBranches:number;durationMs:number;timedOut:boolean}; }
export interface TimetableSolverOptions { maxBranches?:number; timeoutMs?:number; baselineEntries?:TimetableEntry[]; preferredMorningAssignmentIds?:string[]; }
export interface TimetableSolver { solve(problem:ScheduleProblem,options?:TimetableSolverOptions):SolverResult; }

type Candidate={day:StudyDay;periodIds:string[]};
function candidatesFor(assignment:PedagogicalAssignment,problem:ScheduleProblem):Candidate[]{const periods=getActiveCoursePeriods(problem.periods);const size=assignment.blockSize??1;const result:Candidate[]=[];for(const day of STUDY_DAYS){for(let i=0;i<periods.length;i+=1){const block=periods.slice(i,i+size);if(block.length!==size)continue;if(size===2&&!adjacentCoursePeriods(block[0],block[1],problem.periods))continue;if(block.every(period=>teacherAvailableAt(assignment.teacherId,day,period,problem.availabilities)))result.push({day,periodIds:block.map(period=>period.id)});}}return result;}

export class DeterministicTimetableSolver implements TimetableSolver{
  solve(problem:ScheduleProblem,options:TimetableSolverOptions={}):SolverResult{
    const started=Date.now(),deadline=started+(options.timeoutMs??2000),maxBranches=options.maxBranches??100000;let exploredBranches=0,timedOut=false;
    const active=problem.assignments.filter(item=>item.active);const invalidScope=active.find(item=>item.schoolId!==problem.schoolId||item.schoolYearId!==problem.schoolYearId);
    if(invalidScope)return{success:false,entries:[],failures:[{assignmentId:invalidScope.id,teacherId:invalidScope.teacherId,classId:invalidScope.classId,subjectId:invalidScope.subjectId,required:invalidScope.weeklyPeriods,availableCapacity:0,reason:"Affectation hors école ou année scolaire."}],statistics:{exploredBranches,durationMs:Date.now()-started,timedOut}};
    const jobs=active.map(assignment=>({assignment,blockSize:assignment.blockSize??1,blocks:assignment.weeklyPeriods/(assignment.blockSize??1),candidates:candidatesFor(assignment,problem)})).sort((a,b)=>a.candidates.length-b.candidates.length||b.blockSize-a.blockSize||b.assignment.weeklyPeriods-a.assignment.weeklyPeriods||a.assignment.id.localeCompare(b.assignment.id));
    const impossible=jobs.find(job=>!Number.isInteger(job.blocks)||job.candidates.length<job.blocks);if(impossible)return{success:false,entries:[],failures:[{assignmentId:impossible.assignment.id,teacherId:impossible.assignment.teacherId,classId:impossible.assignment.classId,subjectId:impossible.assignment.subjectId,required:impossible.assignment.weeklyPeriods,availableCapacity:impossible.candidates.length*impossible.blockSize,reason:impossible.blockSize===2&&impossible.assignment.weeklyPeriods%2?"Le volume d’un cours double doit être pair.":"Nombre insuffisant de créneaux compatibles."}],statistics:{exploredBranches,durationMs:Date.now()-started,timedOut}};
    const baselineByAssignment=new Map<string,TimetableEntry[]>();for(const entry of options.baselineEntries??[]){const list=baselineByAssignment.get(entry.assignmentId)??[];list.push(entry);baselineByAssignment.set(entry.assignmentId,list)}const morning=new Set(options.preferredMorningAssignmentIds??[]);const candidateCost=(assignment:PedagogicalAssignment,index:number,candidate:Candidate)=>{const baseline=[...(baselineByAssignment.get(assignment.id)??[])].sort((a,b)=>`${a.dayOfWeek}-${a.periodId}`.localeCompare(`${b.dayOfWeek}-${b.periodId}`));const prior=baseline[index*(assignment.blockSize??1)];let cost=prior?(prior.dayOfWeek===candidate.day?(prior.periodId===candidate.periodIds[0]?0:1):4):2;if(morning.has(assignment.id))cost+=candidate.periodIds.some(id=>problem.periods.find(p=>p.id===id)?.order&&Number(problem.periods.find(p=>p.id===id)!.order)>Math.ceil(getActiveCoursePeriods(problem.periods).length/2))?3:0;return cost};
    const tasks=jobs.flatMap(job=>Array.from({length:job.blocks},(_,index)=>({assignment:job.assignment,index,candidates:[...job.candidates].sort((a,b)=>candidateCost(job.assignment,index,a)-candidateCost(job.assignment,index,b)||`${a.day}-${a.periodIds.join()}`.localeCompare(`${b.day}-${b.periodIds.join()}`))})));const selected:Array<{assignment:PedagogicalAssignment;index:number;candidate:Candidate}>=[];const teacherBusy=new Set<string>(),classBusy=new Set<string>(),roomBusy=new Set<string>();const daily=new Map<string,number>();
    const search=(position:number):boolean=>{if(position===tasks.length)return true;if(++exploredBranches>maxBranches||Date.now()>deadline){timedOut=true;return false;}const task=tasks[position];for(const candidate of task.candidates){const countKey=`${task.assignment.id}|${candidate.day}`;if((daily.get(countKey)||0)+candidate.periodIds.length>(problem.maxSameAssignmentPeriodsPerDay??DEFAULT_MAX_SAME_ASSIGNMENT_PERIODS_PER_DAY))continue;if(candidate.periodIds.some(periodId=>teacherBusy.has(`${task.assignment.teacherId}|${candidate.day}|${periodId}`)||classBusy.has(`${task.assignment.classId}|${candidate.day}|${periodId}`)||(task.assignment.preferredRoomId&&roomBusy.has(`${task.assignment.preferredRoomId}|${candidate.day}|${periodId}`))))continue;candidate.periodIds.forEach(periodId=>{teacherBusy.add(`${task.assignment.teacherId}|${candidate.day}|${periodId}`);classBusy.add(`${task.assignment.classId}|${candidate.day}|${periodId}`);if(task.assignment.preferredRoomId)roomBusy.add(`${task.assignment.preferredRoomId}|${candidate.day}|${periodId}`)});daily.set(countKey,(daily.get(countKey)||0)+candidate.periodIds.length);selected.push({assignment:task.assignment,index:task.index,candidate});if(search(position+1))return true;selected.pop();daily.set(countKey,(daily.get(countKey)||0)-candidate.periodIds.length);candidate.periodIds.forEach(periodId=>{teacherBusy.delete(`${task.assignment.teacherId}|${candidate.day}|${periodId}`);classBusy.delete(`${task.assignment.classId}|${candidate.day}|${periodId}`);if(task.assignment.preferredRoomId)roomBusy.delete(`${task.assignment.preferredRoomId}|${candidate.day}|${periodId}`)});if(timedOut)return false;}return false;};
    const solved=search(0);if(!solved){const first=jobs[0];return{success:false,entries:[],failures:[{assignmentId:first?.assignment.id??"unknown",teacherId:first?.assignment.teacherId??"",classId:first?.assignment.classId??"",subjectId:first?.assignment.subjectId??"",required:first?.assignment.weeklyPeriods??0,availableCapacity:first?.candidates.length??0,reason:timedOut?"Temps maximal de résolution dépassé.":"Les contraintes enseignant, classe et volume sont incompatibles."}],statistics:{exploredBranches,durationMs:Date.now()-started,timedOut}};}
    const now=new Date().toISOString();const entries=selected.flatMap(({assignment,index,candidate})=>candidate.periodIds.map((periodId):TimetableEntry=>({id:`${assignment.id}__${candidate.day}__${periodId}`,scheduleId:"pending",schoolId:problem.schoolId,schoolYearId:problem.schoolYearId,classId:assignment.classId,teacherId:assignment.teacherId,subjectId:assignment.subjectId,assignmentId:assignment.id,dayOfWeek:candidate.day,periodId,roomId:assignment.preferredRoomId??null,...((assignment.blockSize??1)>1?{blockId:`${assignment.id}__block_${index}`}:{ }),createdAt:now,updatedAt:now})));
    const report=validateTimetable(problem,entries);return{success:report.valid,entries:report.valid?entries:[],failures:report.errors.map(error=>{const assignment=active.find(item=>item.id===error.entityId)||active[0];return{assignmentId:assignment?.id??"unknown",teacherId:assignment?.teacherId??"",classId:assignment?.classId??"",subjectId:assignment?.subjectId??"",required:assignment?.weeklyPeriods??0,availableCapacity:0,reason:error.message}}),statistics:{exploredBranches,durationMs:Date.now()-started,timedOut}};
  }
}
