import { readFileSync } from "node:fs";
import { assertFails, assertSucceeds, initializeTestEnvironment, type RulesTestEnvironment } from "@firebase/rules-unit-testing";
import { collection, doc, getDocs, query, setDoc, where } from "firebase/firestore";
import { afterAll, beforeAll, beforeEach, describe, it } from "vitest";

let env:RulesTestEnvironment;const school="school-a",year="year-a",uid="teacher-user-a",teacher="teacher-a",assignment="assignment-a",now="2026-08-15T10:00:00.000Z";
const context=(id=uid,role="teacher",tenant=school)=>env.authenticatedContext(id,{role,schoolId:tenant}).firestore();
const seed=(path:string,data:Record<string,unknown>)=>env.withSecurityRulesDisabled(admin=>setDoc(doc(admin.firestore(),path),data));
const base={schoolId:school,schoolYearId:year,teacherId:teacher,assignmentId:assignment,classId:"class-a",subjectId:"subject-a",createdAt:now,createdBy:uid,updatedAt:now,updatedBy:uid};
describe("outils pédagogiques Enseignant",()=>{beforeAll(async()=>{env=await initializeTestEnvironment({projectId:"demo-teacher-learning",firestore:{rules:readFileSync("firestore.rules","utf8")}})},30000);beforeEach(async()=>{await env.clearFirestore();await seed(`schools/${school}`,{id:school,status:"active"});await seed(`schoolYears/${year}`,{id:year,schoolId:school,status:"active"});await seed(`users/${uid}`,{id:uid,role:"teacher",schoolId:school,status:"active",active:true});await seed(`teachers/${teacher}`,{id:teacher,userId:uid,schoolId:school,schoolYearId:year,status:"active"});await seed(`classes/class-a`,{id:"class-a",schoolId:school,schoolYearId:year});await seed(`subjects/subject-a`,{id:"subject-a",schoolId:school,schoolYearId:year});await seed(`students/student-a`,{id:"student-a",schoolId:school,schoolYearId:year,classId:"class-a"});await seed(`pedagogicalAssignments/${assignment}`,{id:assignment,schoolId:school,schoolYearId:year,teacherId:teacher,classId:"class-a",subjectId:"subject-a",active:true});});afterAll(()=>env.cleanup());
it("autorise progression, observation et document propres",async()=>{const db=context();await assertSucceeds(setDoc(doc(db,"teachingProgress","progress-a"),{id:"progress-a",...base,title:"Fractions",status:"TODO",periodsUsed:1}));await assertSucceeds(setDoc(doc(db,"teacherStudentObservations","observation-a"),{id:"observation-a",...base,studentId:"student-a",observation:"Bonne progression"}));await assertSucceeds(setDoc(doc(db,"pedagogicalDocuments","document-a"),{id:"document-a",...base,category:"PREPARATION",title:"Préparation",fileUrl:"https://example.invalid",storagePath:"teacher-documents/x",originalFileName:"fiche.pdf",mimeType:"application/pdf",size:100,archived:false}));});
it("autorise les lectures propres tenantées",async()=>{await seed("teachingProgress/progress-a",{id:"progress-a",...base,title:"Fractions",status:"TODO",periodsUsed:1});await assertSucceeds(getDocs(query(collection(context(),"teachingProgress"),where("schoolId","==",school),where("schoolYearId","==",year),where("teacherId","==",teacher))));});
it("refuse autre enseignant, autre école et utilisateur inactif",async()=>{const payload={id:"progress-a",...base,title:"Fractions",status:"TODO",periodsUsed:1};await assertFails(setDoc(doc(context("other"),"teachingProgress","progress-a"),payload));await assertFails(setDoc(doc(context(uid,"teacher","school-b"),"teachingProgress","progress-a"),payload));await seed(`users/${uid}`,{id:uid,role:"teacher",schoolId:school,status:"inactive",active:false});await assertFails(setDoc(doc(context(),"teachingProgress","progress-a"),payload));});
it("refuse une affectation ou un élève hors périmètre",async()=>{await assertFails(setDoc(doc(context(),"teachingProgress","progress-a"),{id:"progress-a",...base,assignmentId:"unknown",title:"X",status:"TODO",periodsUsed:1}));await assertFails(setDoc(doc(context(),"teacherStudentObservations","observation-a"),{id:"observation-a",...base,studentId:"unknown",observation:"X"}));});});
