import { readFileSync } from "node:fs";
import { assertFails,assertSucceeds,initializeTestEnvironment,type RulesTestEnvironment } from "@firebase/rules-unit-testing";
import { collection,doc,getDoc,getDocs,query,setDoc,updateDoc,where } from "firebase/firestore";
import { afterAll,beforeAll,beforeEach,describe,it } from "vitest";

let env:RulesTestEnvironment;const school="school-a",year="year-a",uid="teacher-user-a",teacher="teacher-a",now="2026-08-10T10:00:00.000Z";
const context=(role="teacher",tenant=school,id=uid)=>env.authenticatedContext(id,{role,schoolId:tenant}).firestore();
const seed=(path:string,data:Record<string,unknown>)=>env.withSecurityRulesDisabled(c=>setDoc(doc(c.firestore(),path),data));
const request=(overrides:Record<string,unknown>={})=>({id:"request-a",schoolId:school,schoolYearId:year,teacherId:teacher,userId:uid,requestedDate:"2026-08-20",requestType:"TIME_RANGE",startTime:"10:00",endTime:"12:00",reason:"Obligation personnelle",status:"PENDING",createdAt:now,createdBy:uid,...overrides});
const fullDayRequest=()=>{const value=request({requestType:"FULL_DAY"}) as Record<string,unknown>;delete value.startTime;delete value.endTime;return value};

describe("Phase 4 demandes d’indisponibilité",()=>{beforeAll(async()=>{env=await initializeTestEnvironment({projectId:"demo-teacher-requests",firestore:{rules:readFileSync("firestore.rules","utf8")}})},30000);beforeEach(async()=>{await env.clearFirestore();await seed(`schools/${school}`,{id:school,status:"active"});await seed(`schoolYears/${year}`,{id:year,schoolId:school,status:"active"});await seed(`users/${uid}`,{id:uid,role:"teacher",schoolId:school,status:"active",active:true});await seed(`teachers/${teacher}`,{id:teacher,userId:uid,schoolId:school,schoolYearId:year,status:"active"})});afterAll(()=>env.cleanup());
  it("autorise la création PENDING propre et la lecture ciblée",async()=>{await assertSucceeds(setDoc(doc(context(),"teacherAvailabilityRequests","request-a"),request()));await assertSucceeds(getDocs(query(collection(context(),"teacherAvailabilityRequests"),where("schoolId","==",school),where("schoolYearId","==",year),where("teacherId","==",teacher),where("userId","==",uid))))});
  it("autorise journée complète sans heures",async()=>{await assertSucceeds(setDoc(doc(context(),"teacherAvailabilityRequests","request-a"),fullDayRequest())) });
  it("refuse autre teacher, autre école et statut forcé",async()=>{await assertFails(setDoc(doc(context(),"teacherAvailabilityRequests","request-a"),request({teacherId:"teacher-b"})));await assertFails(setDoc(doc(context(),"teacherAvailabilityRequests","request-a"),request({schoolId:"school-b"})));await assertFails(setDoc(doc(context(),"teacherAvailabilityRequests","request-a"),request({status:"APPROVED"}))) });
  it("refuse la décision directe par teacher et les autres rôles",async()=>{await seed("teacherAvailabilityRequests/request-a",request());await assertFails(updateDoc(doc(context(),"teacherAvailabilityRequests","request-a"),{status:"APPROVED"}));await assertFails(getDoc(doc(context("secretary",school,"secretary"),"teacherAvailabilityRequests","request-a")));await assertFails(getDoc(doc(context("cashier",school,"cashier"),"teacherAvailabilityRequests","request-a"))) });
  it("autorise study_director même école en lecture mais jamais en écriture directe",async()=>{await seed("teacherAvailabilityRequests/request-a",request());await assertSucceeds(getDoc(doc(context("study_director",school,"director"),"teacherAvailabilityRequests","request-a")));await assertFails(updateDoc(doc(context("study_director",school,"director"),"teacherAvailabilityRequests","request-a"),{status:"REJECTED"})) });
  it("refuse study_director autre école et teacher autre identité",async()=>{await seed("teacherAvailabilityRequests/request-a",request());await assertFails(getDoc(doc(context("study_director","school-b","director-b"),"teacherAvailabilityRequests","request-a")));await assertFails(getDoc(doc(context("teacher",school,"teacher-user-b"),"teacherAvailabilityRequests","request-a"))) });
  it("refuse un teacher archivé",async()=>{await seed(`users/${uid}`,{id:uid,role:"teacher",schoolId:school,status:"inactive",active:false});await assertFails(setDoc(doc(context(),"teacherAvailabilityRequests","request-a"),request()))});
});
