import { useMemo, useState, type ReactNode } from "react";
import { BookOpen, CalendarDays, ClipboardPenLine, FileText, UserRoundCheck } from "lucide-react";
import { LogoutButton } from "../../components/ui";
import { TeacherBottomNavigation } from "../../components/layout/TeacherBottomNavigation";
import type { TeacherTab } from "../../components/layout/teacherNavigation";
import type { AppUser, School, SchoolYear } from "../../types";
import { currentStudyDay, nextTeacherEntry, orderedStudyDays, studyDayLabels, teacherEntriesForDay, weeklyWorkload } from "./teacherPortalData";
import { useTeacherPortalData } from "./useTeacherPortalData";
import { TeacherAvailabilityRequestsDrawer } from "./TeacherAvailabilityRequestsDrawer";
import { TeacherGradingDrawer } from "./TeacherGradingDrawer";

export function TeacherPortal({ user, school, year, renderHeader, renderEnvironmentBanner, onLogout }: { user: AppUser; school: School; year: SchoolYear; renderHeader: () => ReactNode; renderEnvironmentBanner: () => ReactNode; onLogout: () => void }) {
  const [activeTab, setActiveTab] = useState<TeacherTab>("dashboard");
  const [requestsOpen, setRequestsOpen] = useState(false);
  const [gradingOpen, setGradingOpen] = useState(false);
  const data = useTeacherPortalData(user, school.id, year.id);
  const periods = useMemo(() => [...data.periods].filter((item) => item.active).sort((left, right) => left.order - right.order), [data.periods]);
  const today = useMemo(() => teacherEntriesForDay(data.entries, periods, currentStudyDay()), [data.entries, periods]);
  const next = useMemo(() => nextTeacherEntry(data.entries, periods), [data.entries, periods]);
  const label = (items: Array<{ id: string; name: string }>, id: string, fallback: string) => items.find((item) => item.id === id)?.name ?? fallback;
  const periodLabel = (id: string) => { const period = periods.find((item) => item.id === id); return period ? `${period.label} · ${period.startTime}–${period.endTime}` : id; };
  const courseCard = (entry: (typeof data.entries)[number]) => <article key={entry.id} className="rounded border border-slate-200 bg-white p-4 shadow-sm"><p className="font-bold text-ink">{label(data.subjects, entry.subjectId, "Matière non renseignée")}</p><p className="mt-1 text-sm text-slate-600">{label(data.classes, entry.classId, "Classe non renseignée")} · {periodLabel(entry.periodId)}</p><p className="mt-1 text-xs font-semibold text-blue-700">Salle : {entry.roomId ? label(data.rooms, entry.roomId, "Non renseignée") : "Non renseignée"}</p></article>;

  return <div className="flex h-screen flex-col overflow-hidden bg-[#f6f8fb]">{renderEnvironmentBanner()}{renderHeader()}<main className="mx-auto w-full max-w-7xl min-w-0 flex-1 overflow-y-auto px-3 py-5 pb-28 sm:px-6 sm:pb-32 lg:px-8">
    {data.loading && <p className="rounded bg-white p-6 text-center text-sm text-slate-500">Chargement de votre espace Enseignant…</p>}
    {data.error && <p role="alert" className="rounded border border-red-200 bg-red-50 p-4 text-sm font-semibold text-red-700">{data.error}</p>}
    {!data.loading && data.teacher && activeTab === "dashboard" && <section className="grid gap-4"><div><h1 className="text-2xl font-bold text-ink">Tableau de bord Enseignant</h1><p className="mt-1 text-sm text-slate-600">{school.name} · Année scolaire {year.name}</p></div><div className="grid gap-3 sm:grid-cols-3">{[["Cours aujourd’hui", today.length], ["Charge hebdomadaire", `${weeklyWorkload(data.assignments)} périodes`], ["Affectations actives", data.assignments.length]].map(([title, value]) => <article key={title} className="rounded border border-slate-200 bg-white p-4 shadow-sm"><p className="text-xs font-semibold uppercase text-slate-500">{title}</p><p className="mt-2 text-2xl font-bold text-ink">{value}</p></article>)}</div><div className="grid gap-4 lg:grid-cols-2"><section className="grid content-start gap-2"><h2 className="text-lg font-bold text-ink">Cours du jour</h2>{today.length ? today.map(courseCard) : <p className="rounded bg-white p-4 text-sm text-slate-500">Aucun cours aujourd’hui.</p>}</section><section className="grid content-start gap-2"><h2 className="text-lg font-bold text-ink">Prochain cours</h2>{next ? courseCard(next) : <p className="rounded bg-white p-4 text-sm text-slate-500">Aucun autre cours aujourd’hui.</p>}</section></div></section>}
    {!data.loading && data.teacher && activeTab === "courses" && <section className="grid gap-4"><div><h1 className="text-2xl font-bold text-ink">Mes cours</h1><p className="text-sm text-slate-600">Affectations définies par la Direction des études, en lecture seule.</p></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{data.assignments.map((assignment) => <article key={assignment.id} className="rounded border border-slate-200 bg-white p-4 shadow-sm"><p className="font-bold text-ink">{label(data.subjects, assignment.subjectId, "Matière non renseignée")}</p><p className="mt-1 text-sm text-slate-600">{label(data.classes, assignment.classId, "Classe non renseignée")}</p><p className="mt-3 text-sm font-semibold text-blue-700">{assignment.weeklyPeriods} périodes/semaine</p>{assignment.preferredRoomId && <p className="mt-1 text-xs text-slate-500">Salle préférée : {label(data.rooms, assignment.preferredRoomId, "Non renseignée")}</p>}<span className="mt-3 inline-block rounded-full bg-green-100 px-2 py-1 text-xs font-semibold text-green-800">Actif</span></article>)}{data.assignments.length === 0 && <p className="rounded bg-white p-5 text-sm text-slate-500">Aucune affectation active.</p>}</div></section>}
    {!data.loading && data.teacher && activeTab === "schedule" && <section className="grid gap-4" data-active-schedule-id={data.activeTimetable?.id ?? "none"}><div><h1 className="text-2xl font-bold text-ink">Mon horaire</h1><p className="text-sm text-slate-600">Horaire publié actif, en lecture seule.{data.activeTimetable ? ` Version ${data.activeTimetable.version}.` : ""}</p></div>{data.entries.length === 0 ? <p className="rounded bg-white p-5 text-sm text-slate-500">Aucun horaire publié pour cette année scolaire.</p> : <div className="grid gap-4">{orderedStudyDays.map((day) => { const entries = teacherEntriesForDay(data.entries, periods, day); if (!entries.length) return null; return <section key={day} className="rounded border border-slate-200 bg-white p-4 shadow-sm"><h2 className="font-bold text-ink">{studyDayLabels[day]}</h2><div className="mt-3 grid gap-2">{entries.map(courseCard)}</div></section>; })}</div>}</section>}
    {!data.loading && data.teacher && activeTab === "menu" && <section className="grid gap-4"><div><h1 className="text-2xl font-bold text-ink">Menu</h1><p className="text-sm text-slate-600">Fonctions secondaires de votre espace.</p></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><button type="button" onClick={()=>setGradingOpen(true)} className="rounded border border-slate-200 bg-white p-4 text-left text-ink shadow-sm transition hover:bg-slate-50 focus:outline-none focus:ring-2 focus:ring-blue-600"><ClipboardPenLine className="h-5 w-5"/><p className="mt-2 font-semibold">Fiche de cotation</p><p className="mt-1 text-xs text-slate-500">Saisie et consolidation</p></button>{[[BookOpen,"Ma progression pédagogique"],[CalendarDays,"Mes disponibilités"],[FileText,"Documents pédagogiques"]].map(([Icon, title]) => { const Component = Icon as typeof BookOpen; return <article key={String(title)} aria-disabled="true" className="rounded border border-slate-200 bg-white p-4 text-slate-500 shadow-sm"><Component className="h-5 w-5"/><p className="mt-2 font-semibold">{String(title)}</p><p className="mt-1 text-xs">Bientôt disponible</p></article>; })}<button type="button" onClick={()=>setRequestsOpen(true)} className="rounded border border-slate-200 bg-white p-4 text-left text-ink shadow-sm transition hover:bg-slate-50 focus:outline-none focus:ring-2 focus:ring-blue-600"><UserRoundCheck className="h-5 w-5"/><p className="mt-2 font-semibold">Mes demandes</p><p className="mt-1 text-xs text-slate-500">Indisponibilités</p></button></div><LogoutButton onClick={onLogout} /></section>}
    {requestsOpen&&data.teacher&&<TeacherAvailabilityRequestsDrawer user={user} school={school} year={year} teacher={data.teacher} onClose={()=>setRequestsOpen(false)}/>}
    {gradingOpen&&<TeacherGradingDrawer school={school} year={year} onClose={()=>setGradingOpen(false)}/>}
  </main><TeacherBottomNavigation activeTab={activeTab} onTab={setActiveTab}/></div>;
}
