import { useMemo, useState, type ReactNode } from "react";
import { BookOpen, CalendarDays, ClipboardPenLine, Clock3, FileText, Gauge, Users, UserRoundCheck } from "lucide-react";
import { DashboardCard, FormPanel, LogoutButton } from "../../components/ui";
import { TeacherBottomNavigation } from "../../components/layout/TeacherBottomNavigation";
import type { TeacherTab } from "../../components/layout/teacherNavigation";
import type { AppUser, School, SchoolYear } from "../../types";
import { currentStudyDay, nextTeacherEntry, orderedStudyDays, studyDayLabels, teacherEntriesForDay, weeklyWorkload } from "./teacherPortalData";
import { useTeacherPortalData } from "./useTeacherPortalData";
import { TeacherAvailabilityRequestsDrawer } from "./TeacherAvailabilityRequestsDrawer";
import { TeacherGradingDrawer } from "./TeacherGradingDrawer";
import { TeacherProgressDrawer } from "./TeacherProgressDrawer";
import { TeacherStudentsDrawer } from "./TeacherStudentsDrawer";
import { TeacherDocumentsDrawer } from "./TeacherDocumentsDrawer";

export function TeacherPortal({ user, school, year, refreshToken = 0, renderHeader, renderEnvironmentBanner, onLogout }: { user: AppUser; school: School; year: SchoolYear; refreshToken?: number; renderHeader: () => ReactNode; renderEnvironmentBanner: () => ReactNode; onLogout: () => void }) {
  const [activeTab, setActiveTab] = useState<TeacherTab>("dashboard");
  const [requestsOpen, setRequestsOpen] = useState(false);
  const [gradingOpen, setGradingOpen] = useState(false);
  const [progressOpen, setProgressOpen] = useState(false);
  const [studentsOpen, setStudentsOpen] = useState(false);
  const [documentsOpen, setDocumentsOpen] = useState(false);
  const data = useTeacherPortalData(user, school.id, year.id, refreshToken);
  const periods = useMemo(() => [...data.periods].filter((item) => item.active).sort((left, right) => left.order - right.order), [data.periods]);
  const today = useMemo(() => teacherEntriesForDay(data.entries, periods, currentStudyDay()), [data.entries, periods]);
  const next = useMemo(() => nextTeacherEntry(data.entries, periods), [data.entries, periods]);
  const label = (items: Array<{ id: string; name: string }>, id: string, fallback: string) => items.find((item) => item.id === id)?.name ?? fallback;
  const periodLabel = (id: string) => { const period = periods.find((item) => item.id === id); return period ? `${period.label} · ${period.startTime}–${period.endTime}` : id; };
  const courseDetails = (entry: (typeof data.entries)[number]) => <div key={entry.id} className="border-t border-slate-100 py-2 first:border-t-0 first:pt-0 last:pb-0"><p className="font-bold text-ink">{label(data.subjects, entry.subjectId, "Matière non renseignée")}</p><p className="mt-1 text-sm text-slate-600">{label(data.classes, entry.classId, "Classe non renseignée")} · {periodLabel(entry.periodId)}</p><p className="mt-1 text-xs font-semibold text-blue-700">Salle : {entry.roomId ? label(data.rooms, entry.roomId, "Non renseignée") : "Non renseignée"}</p></div>;
  const courseCard = (entry: (typeof data.entries)[number]) => <article key={entry.id} className="rounded border border-slate-200 bg-white p-4 shadow-sm">{courseDetails(entry)}</article>;

  return <div className="flex h-screen flex-col overflow-hidden bg-[#f6f8fb]">{renderEnvironmentBanner()}{renderHeader()}<main className="mx-auto w-full max-w-7xl min-w-0 flex-1 overflow-y-auto px-3 py-5 pb-28 sm:px-6 sm:pb-32 lg:px-8">
    {data.loading && <p className="rounded bg-white p-6 text-center text-sm text-slate-500">Chargement de votre espace Enseignant…</p>}
    {data.error && <p role="alert" className="rounded border border-red-200 bg-red-50 p-4 text-sm font-semibold text-red-700">{data.error}</p>}
    {!data.loading && data.teacher && activeTab === "dashboard" && <section className="grid gap-4"><div><h1 className="text-2xl font-bold text-ink">Dashboard Enseignant</h1><p className="mt-1 text-sm text-slate-600">{school.name} · Année scolaire {year.name}</p></div><div className="grid min-w-0 grid-cols-1 gap-4 sm:grid-cols-2"><DashboardCard title="Cours aujourd’hui" icon={CalendarDays}>{today.length ? <div className="grid gap-2">{today.map(courseDetails)}</div> : <p className="text-sm text-slate-500">Aucun cours aujourd’hui.</p>}</DashboardCard><DashboardCard title="Charge hebdomadaire" icon={Gauge} tone="bg-emerald-50 text-emerald-700" value={`${weeklyWorkload(data.assignments)} périodes`} /><DashboardCard title="Affectations actives" icon={ClipboardPenLine} tone="bg-amber-50 text-amber-700" value={data.assignments.length} /><DashboardCard title="Prochain cours" icon={Clock3} tone="bg-violet-50 text-violet-700">{next ? courseDetails(next) : <p className="text-sm text-slate-500">Aucun prochain cours.</p>}</DashboardCard></div></section>}
    {!data.loading && data.teacher && activeTab === "courses" && <section className="grid gap-4"><div><h1 className="text-2xl font-bold text-ink">Mes cours</h1><p className="text-sm text-slate-600">Affectations définies par la Direction des études, en lecture seule.</p></div><FormPanel title=""><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{data.assignments.map((assignment) => <article key={assignment.id} className="rounded border border-slate-200 bg-white p-4 shadow-sm"><p className="font-bold text-ink">{label(data.subjects, assignment.subjectId, "Matière non renseignée")}</p><p className="mt-1 text-sm text-slate-600">{label(data.classes, assignment.classId, "Classe non renseignée")}</p><p className="mt-3 text-sm font-semibold text-blue-700">{assignment.weeklyPeriods} périodes/semaine</p>{assignment.preferredRoomId && <p className="mt-1 text-xs text-slate-500">Salle préférée : {label(data.rooms, assignment.preferredRoomId, "Non renseignée")}</p>}<span className="mt-3 inline-block rounded-full bg-green-100 px-2 py-1 text-xs font-semibold text-green-800">Actif</span></article>)}{data.assignments.length === 0 && <p className="text-sm text-slate-500">Aucune affectation active.</p>}</div></FormPanel></section>}
    {!data.loading && data.teacher && activeTab === "schedule" && <section className="grid gap-4" data-active-schedule-id={data.activeTimetable?.id ?? "none"}><div><h1 className="text-2xl font-bold text-ink">Mon horaire</h1><p className="text-sm text-slate-600">Horaire publié actif, en lecture seule.{data.activeTimetable ? ` Version ${data.activeTimetable.version}.` : ""}</p></div><FormPanel title="">{data.entries.length === 0 ? <p className="text-sm text-slate-500">Aucun horaire publié pour cette année scolaire.</p> : <div className="grid gap-4">{orderedStudyDays.map((day) => { const entries = teacherEntriesForDay(data.entries, periods, day); if (!entries.length) return null; return <section key={day} className="rounded border border-slate-200 bg-white p-4 shadow-sm"><h2 className="font-bold text-ink">{studyDayLabels[day]}</h2><div className="mt-3 grid gap-2">{entries.map(courseCard)}</div></section>; })}</div>}</FormPanel></section>}
    {!data.loading && data.teacher && activeTab === "menu" && <section className="grid gap-4"><div><h1 className="text-2xl font-bold text-ink">Menu</h1><p className="text-sm text-slate-600">Fonctions secondaires de votre espace.</p></div><div className="grid gap-3"><button type="button" onClick={()=>setGradingOpen(true)} className="rounded border border-slate-200 bg-white p-4 text-left text-ink shadow-sm transition hover:bg-slate-50 focus:outline-none focus:ring-2 focus:ring-blue-600"><span className="flex items-center gap-3"><ClipboardPenLine className="h-5 w-5 shrink-0"/><span className="font-semibold">Fiche de cotation</span></span><p className="mt-1 pl-8 text-xs text-slate-500">Saisie et consolidation</p></button><button type="button" onClick={()=>setProgressOpen(true)} className="rounded border border-slate-200 bg-white p-4 text-left text-ink shadow-sm transition hover:bg-slate-50 focus:outline-none focus:ring-2 focus:ring-blue-600"><span className="flex items-center gap-3"><BookOpen className="h-5 w-5 shrink-0"/><span className="font-semibold">Ma progression pédagogique</span></span><p className="mt-1 pl-8 text-xs text-slate-500">Suivi des matières enseignées</p></button><button type="button" onClick={()=>setStudentsOpen(true)} className="rounded border border-slate-200 bg-white p-4 text-left text-ink shadow-sm transition hover:bg-slate-50 focus:outline-none focus:ring-2 focus:ring-blue-600"><span className="flex items-center gap-3"><Users className="h-5 w-5 shrink-0"/><span className="font-semibold">Mes élèves</span></span><p className="mt-1 pl-8 text-xs text-slate-500">Suivi de mes classes</p></button><button type="button" onClick={()=>setDocumentsOpen(true)} className="rounded border border-slate-200 bg-white p-4 text-left text-ink shadow-sm transition hover:bg-slate-50 focus:outline-none focus:ring-2 focus:ring-blue-600"><span className="flex items-center gap-3"><FileText className="h-5 w-5 shrink-0"/><span className="font-semibold">Documents pédagogiques</span></span><p className="mt-1 pl-8 text-xs text-slate-500">Préparations et ressources</p></button><button type="button" onClick={()=>setRequestsOpen(true)} className="rounded border border-slate-200 bg-white p-4 text-left text-ink shadow-sm transition hover:bg-slate-50 focus:outline-none focus:ring-2 focus:ring-blue-600"><span className="flex items-center gap-3"><UserRoundCheck className="h-5 w-5 shrink-0"/><span className="font-semibold">Mes demandes</span></span><p className="mt-1 pl-8 text-xs text-slate-500">Indisponibilités</p></button></div><LogoutButton onClick={onLogout} /></section>}
    {requestsOpen&&data.teacher&&<TeacherAvailabilityRequestsDrawer user={user} school={school} year={year} teacher={data.teacher} onClose={()=>setRequestsOpen(false)}/>}
    {gradingOpen&&<TeacherGradingDrawer user={user} school={school} year={year} onClose={()=>setGradingOpen(false)}/>}
    {progressOpen&&<TeacherProgressDrawer user={user} school={school} year={year} data={data} onClose={()=>setProgressOpen(false)}/>}
    {studentsOpen&&<TeacherStudentsDrawer user={user} school={school} year={year} data={data} onClose={()=>setStudentsOpen(false)}/>}
    {documentsOpen&&<TeacherDocumentsDrawer user={user} school={school} year={year} data={data} onClose={()=>setDocumentsOpen(false)}/>}
  </main><TeacherBottomNavigation activeTab={activeTab} onTab={setActiveTab}/></div>;
}
