import { useEffect, useState } from "react";
import { AdminDrawer } from "../../components/ui";
import type { AppUser, School, SchoolYear } from "../../types";
import { availabilityRequestLabels, type AvailabilityRequestType, type TeacherAvailabilityRequest } from "../studies/teacherAvailabilityRequests";
import type { StudyTeacher } from "../studies/studyTypes";
import { createAvailabilityRequest, subscribeToOwnAvailabilityRequests } from "./teacherAvailabilityRequestService";

export function TeacherAvailabilityRequestsDrawer({ user, school, year, teacher, onClose }: { user: AppUser; school: School; year: SchoolYear; teacher: StudyTeacher; onClose: () => void }) {
  const [items,setItems]=useState<TeacherAvailabilityRequest[]>([]); const [form,setForm]=useState(false); const [date,setDate]=useState(""); const [type,setType]=useState<AvailabilityRequestType>("FULL_DAY"); const [start,setStart]=useState(""); const [end,setEnd]=useState(""); const [reason,setReason]=useState(""); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
  useEffect(()=>subscribeToOwnAvailabilityRequests({user,schoolId:school.id,schoolYearId:year.id,teacherId:teacher.id,onData:setItems,onError:cause=>setError(cause.message)}),[school.id,teacher.id,user,year.id]);
  async function submit(){if(busy)return;setBusy(true);setError("");try{await createAvailabilityRequest({user,schoolId:school.id,schoolYearId:year.id,teacherId:teacher.id,requestedDate:date,requestType:type,startTime:start,endTime:end,reason,existing:items});setForm(false);setDate("");setType("FULL_DAY");setStart("");setEnd("");setReason("")}catch(cause){setError(cause instanceof Error?cause.message:"Création impossible.")}finally{setBusy(false)}}
  return <AdminDrawer title="Mes demandes d’indisponibilité" closeLabel="Fermer" onClose={()=>!busy&&onClose()}>{!form&&<button className="primary-button w-full justify-center" type="button" onClick={()=>setForm(true)}>Nouvelle demande</button>}{form&&<div className="grid gap-3 rounded border border-slate-200 p-4"><label className="grid gap-1 text-sm font-semibold">Date<input className="input" type="date" min={new Date().toISOString().slice(0,10)} value={date} onChange={e=>setDate(e.target.value)}/></label><label className="grid gap-1 text-sm font-semibold">Type d’indisponibilité<select className="input" value={type} onChange={e=>setType(e.target.value as AvailabilityRequestType)}><option value="FULL_DAY">Journée complète</option><option value="TIME_RANGE">Plage horaire</option></select></label>{type==="TIME_RANGE"&&<div className="grid grid-cols-2 gap-2"><label className="grid gap-1 text-sm font-semibold">Heure de début<input className="input" type="time" value={start} onChange={e=>setStart(e.target.value)}/></label><label className="grid gap-1 text-sm font-semibold">Heure de fin<input className="input" type="time" value={end} onChange={e=>setEnd(e.target.value)}/></label></div>}<label className="grid gap-1 text-sm font-semibold">Motif<textarea className="input min-h-24" value={reason} onChange={e=>setReason(e.target.value)}/></label><div className="grid grid-cols-2 gap-2"><button className="secondary-button justify-center" type="button" disabled={busy} onClick={()=>setForm(false)}>Annuler</button><button className="primary-button justify-center" type="button" disabled={busy} onClick={()=>void submit()}>{busy?"Envoi…":"Envoyer"}</button></div></div>}{error&&<p role="alert" className="rounded bg-red-50 p-3 text-sm text-red-700">{error}</p>}<div className="grid gap-3">{items.map(item=><article key={item.id} className="rounded border border-slate-200 bg-white p-4"><div className="flex items-start justify-between gap-2"><strong>{new Date(`${item.requestedDate}T12:00:00`).toLocaleDateString("fr-FR")}</strong><span className={`rounded-full px-2 py-1 text-xs font-semibold ${item.status==="APPROVED"?"bg-green-100 text-green-800":item.status==="REJECTED"?"bg-red-100 text-red-800":"bg-amber-100 text-amber-800"}`}>{availabilityRequestLabels[item.status]}</span></div><p className="mt-1 text-sm">{item.requestType==="FULL_DAY"?"Journée complète":`${item.startTime} – ${item.endTime}`}</p><p className="mt-2 text-sm text-slate-600">{item.reason}</p><p className="mt-2 text-xs text-slate-500">Demandée le {new Date(item.createdAt).toLocaleString("fr-FR")}</p>{item.reviewComment&&<p className="mt-2 rounded bg-slate-50 p-2 text-sm">Réponse : {item.reviewComment}</p>}</article>)}{!items.length&&<p className="text-sm text-slate-500">Aucune demande.</p>}</div></AdminDrawer>
}
